INSERT INTO job_departamentos VALUES ( 'CO','05',NULL,'Antioquia');
INSERT INTO job_departamentos VALUES ( 'CO','08',NULL,'Atlántico');
INSERT INTO job_departamentos VALUES ( 'CO','11',NULL,'Bogotá');
INSERT INTO job_departamentos VALUES ( 'CO','13',NULL,'Bolivar');
INSERT INTO job_departamentos VALUES ( 'CO','15',NULL,'Boyacá');
INSERT INTO job_departamentos VALUES ( 'CO','17',NULL,'Caldas');
INSERT INTO job_departamentos VALUES ( 'CO','18',NULL,'Caquetá');
INSERT INTO job_departamentos VALUES ( 'CO','19',NULL,'Cauca');
INSERT INTO job_departamentos VALUES ( 'CO','20',NULL,'Cesar');
INSERT INTO job_departamentos VALUES ( 'CO','23',NULL,'Córdoba');
INSERT INTO job_departamentos VALUES ( 'CO','25',NULL,'Cundinamarca');
INSERT INTO job_departamentos VALUES ( 'CO','27',NULL,'Chocó');
INSERT INTO job_departamentos VALUES ( 'CO','41',NULL,'Huila');
INSERT INTO job_departamentos VALUES ( 'CO','44',NULL,'La Guajira');
INSERT INTO job_departamentos VALUES ( 'CO','47',NULL,'Magdalena');
INSERT INTO job_departamentos VALUES ( 'CO','50',NULL,'Meta');
INSERT INTO job_departamentos VALUES ( 'CO','52',NULL,'Nariño');
INSERT INTO job_departamentos VALUES ( 'CO','54',NULL,'Norte de Santander');
INSERT INTO job_departamentos VALUES ( 'CO','63',NULL,'Quindío');
INSERT INTO job_departamentos VALUES ( 'CO','66',NULL,'Risaralda');
INSERT INTO job_departamentos VALUES ( 'CO','68',NULL,'Santander');
INSERT INTO job_departamentos VALUES ( 'CO','70',NULL,'Sucre');
INSERT INTO job_departamentos VALUES ( 'CO','73',NULL,'Tolima');
INSERT INTO job_departamentos VALUES ( 'CO','76',NULL,'Valle del Cauca');
INSERT INTO job_departamentos VALUES ( 'CO','81',NULL,'Arauca');
INSERT INTO job_departamentos VALUES ( 'CO','85',NULL,'Casanare');
INSERT INTO job_departamentos VALUES ( 'CO','86',NULL,'Putumayo');
INSERT INTO job_departamentos VALUES ( 'CO','88',NULL,'San Andrés');
INSERT INTO job_departamentos VALUES ( 'CO','91',NULL,'Amazonas');
INSERT INTO job_departamentos VALUES ( 'CO','94',NULL,'Guainía');
INSERT INTO job_departamentos VALUES ( 'CO','95',NULL,'Guaviare');
INSERT INTO job_departamentos VALUES ( 'CO','97',NULL,'Vaupes');
INSERT INTO job_departamentos VALUES ( 'CO','99',NULL,'Vichada');