INSERT INTO job_departamentos VALUES ( 'CO','05',1,'Antioquia');
INSERT INTO job_departamentos VALUES ( 'CO','08',2,'Atlántico');
INSERT INTO job_departamentos VALUES ( 'CO','11',3,'Bogotá');
INSERT INTO job_departamentos VALUES ( 'CO','13',4,'Bolivar');
INSERT INTO job_departamentos VALUES ( 'CO','15',5,'Boyacá');
INSERT INTO job_departamentos VALUES ( 'CO','17',6,'Caldas');
INSERT INTO job_departamentos VALUES ( 'CO','18',7,'Caquetá');
INSERT INTO job_departamentos VALUES ( 'CO','19',8,'Cauca');
INSERT INTO job_departamentos VALUES ( 'CO','20',9,'Cesar');
INSERT INTO job_departamentos VALUES ( 'CO','23',10,'Córdoba');
INSERT INTO job_departamentos VALUES ( 'CO','25',11,'Cundinamarca');
INSERT INTO job_departamentos VALUES ( 'CO','27',12,'Chocó');
INSERT INTO job_departamentos VALUES ( 'CO','41',13,'Huila');
INSERT INTO job_departamentos VALUES ( 'CO','44',14,'La Guajira');
INSERT INTO job_departamentos VALUES ( 'CO','47',15,'Magdalena');
INSERT INTO job_departamentos VALUES ( 'CO','50',16,'Meta');
INSERT INTO job_departamentos VALUES ( 'CO','52',17,'Nariño');
INSERT INTO job_departamentos VALUES ( 'CO','54',18,'Norte de Santander');
INSERT INTO job_departamentos VALUES ( 'CO','63',19,'Quindío');
INSERT INTO job_departamentos VALUES ( 'CO','66',20,'Risaralda');
INSERT INTO job_departamentos VALUES ( 'CO','68',21,'Santander');
INSERT INTO job_departamentos VALUES ( 'CO','70',22,'Sucre');
INSERT INTO job_departamentos VALUES ( 'CO','73',23,'Tolima');
INSERT INTO job_departamentos VALUES ( 'CO','76',24,'Valle del Cauca');
INSERT INTO job_departamentos VALUES ( 'CO','81',25,'Arauca');
INSERT INTO job_departamentos VALUES ( 'CO','85',26,'Casanare');
INSERT INTO job_departamentos VALUES ( 'CO','86',27,'Putumayo');
INSERT INTO job_departamentos VALUES ( 'CO','88',28,'San Andrés');
INSERT INTO job_departamentos VALUES ( 'CO','91',29,'Amazonas');
INSERT INTO job_departamentos VALUES ( 'CO','94',30,'Guainía');
INSERT INTO job_departamentos VALUES ( 'CO','95',31,'Guaviare');
INSERT INTO job_departamentos VALUES ( 'CO','97',32,'Vaupes');
INSERT INTO job_departamentos VALUES ( 'CO','99',33,'Vichada');