<?php

/**
*
* Copyright (C) 2020 Jobdaily
* Raul Mauricio Oidor Lozano <ozzymauricio75@gmail.com>
*
* Este archivo es parte de:
* Jobdaily:: Sofware empresarial a la medida
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los términos de la Licencia Pública General GNU
* publicada por la Fundación para el Software Libre, ya sea la versión 3
* de la Licencia, o (a su elección) cualquier versión posterior.
*
* Este programa se distribuye con la esperanza de que sea útil, pero
* SIN GARANTÍA ALGUNA; ni siquiera la garantía implícita MERCANTIL o
* de APTITUD PARA UN PROPÓSITO DETERMINADO. Consulte los detalles de
* la Licencia Pública General GNU para obtener una información más
* detallada.
*
* Debería haber recibido una copia de la Licencia Pública General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(
    "GESTARTI"                    => "Articulos",
    "ADICARTI"                    => "Adicionar articulo",
    "CONSARTI"                    => "Consultar articulo",
    "MODIARTI"                    => "Modificar articulo",
    "ELIMARTI"                    => "Eliminar articulo",
    "CODIGO"                      => "Código Articulo",
    "REFERENCIA_PROVEEDOR"        => "Código o referencia del proveedor",
    "DESCRIPCION"                 => "Descripción",
    "FICHA_TECNICA"               => "Ficha tecnica",
    "FOTO"                        => "Foto",
    "ALTO"                        => "Altura(mm)",
    "ANCHO"                       => "Ancho(mm)",
    "PROFUNDIDAD"                 => "Profundidad(mm)",
    "PESO"                        => "Peso(gr)",
    "TIPO_ARTICULO"	              => "Tipo artículo",
    "GARANTIA"                    => "Garantia",
    "GARANTIA_PARTES"             => "Garantia partes",
    "ESTRUCTURA_GRUPO"            => "Estructura grupo",
    "MANEJO_INVENTARIO"           => "Manejo inventario",
    "IMPUESTO_VENTA"              => "Impuesto venta",
    "AYUDA_IMPUESTO_COMPRA"       => "Tasa impuesto de compra",
    "AYUDA_IMPUESTO_VENTA"        => "Tasa impuesto de venta",
    "MARCA"                       => "Marca",
    "DESCRIPCION_MARCA"           => "Descripción Marca",
    "IMPUESTO_COMPRA"             => "Tasa IVA Compra",
    "IMPUESTO_VENTA"              => "Tasa IVA Venta",
    "UNIDAD_COMPRA"               => "Unidad de compra",
    "UNIDAD_VENTA"                => "Unidad de venta",
    "UNIDAD_PRESENTACION"         => "Unidad de presentación",
    "PAIS"                        => "Pais de procedencia",
    "ESTADO"                      => "Estado articulo",
    "PESTANA_GENERAL"             => "General",
    "PESTANA_GRUPO"               => "Grupos",
    "PESTANA_DATOS"               => "Datos operativos",
    "PESTANA_IMAGEN"              => "Imagen",
    "ERROR_EXISTE_CODIGO"         => "Ya existe un artículo con ese código",
    "ERROR_EXISTE_ALFANUMERICO"   => "Ya existe código",
    "ERROR_EXISTE_DESCRIPCION"    => "Ya existe un artículo con esa descripción",
    "ERROR_EXISTE_REFERENCIA"     => "Ya existe una referencia para un código", 
    "ERROR_DATO_ALTO"             => "Digite un valor numerico",
    "AYUDA_CODIGO"                => "Código del artículo",
    "AYUDA_DESCRIPCION"           => "Detalle que describe el artículo",
    "AYUDA_FICHA_TECNICA"         => "Ficha tecnica",
    "AYUDA_FOTO"                  => "Foto del artículo",
    "AYUDA_GARANTIA"              => "Garantia del artículo",
    "AYUDA_GARANTIA_PARTES"       => "Garantia de las partes mas importantes del artículo",
    "PRODUCTO_TERMINADO"          => "Producto terminado",
    "OBSEQUIO"                    => "Obsequio",
    "ACTIVO_FIJO"                 => "Activo fijo",
    "MATERIA_PRIMA"               => "Materia prima",
    "PRODUCTO_TERMINADO"          => "Producto terminado",
    "INVENTARIO_VALORIZADO"       => "Inventario valorizado",
    "INVENTARIO_SOLO_KARDEX"      => "Solo kardex",
    "ACTIVO"                      => "Activo",
    "INACTIVO"                    => "Inactivo",
    "PROVEEDOR"                   => "Proveedor del articulo",
    "AYUDA_PROVEEDOR"             => "Proveedor del articulo",
    "REFERENCIA"                  => "Referencia",
    "REFERENCIA_ALTERNA"          => "Referencia alterna",
    "AYUDA_REFERENCIA"            => "Digite la referencia asignada por el proveedor para este articulo",
    "CODIGO_BARRAS"               => "Código de barras",
    "AYUDA_CODIGO_BARRAS"         => "Si el proveedor maneja código de barras digitelo",
    "AYUDA_ALTO"                  => "Altura del producto en milimetros",
    "AYUDA_ANCHO"                 => "Ancho del producto en milimetros",
    "AYUDA_PROFUNDIDAD"           => "Profundidad del producto en milimetros",
    "AYUDA_PESO"                  => "Peso del producto en milimetros",
    "EXPORTAR"		              => "Exportar",
    "EXPOARTI"		              => "Exportar lista",
    "PESTANA_GRUPOS"	          => "Grupos",
    "PESTANA_PROVEEDORES"         => "Proveedores",
    "PESTANA_MARCAS"	          => "Marcas",
    "PESTANA_ORDEN"	              => "Orden",
    "ESTRUCTURA_GRUPO"	          => "Estructura",
    "CODIGO_ART"	              => "Cód.",
    "ITEM1"		                  => "Categoría",
    "ORDEN1"                      => "de forma",
    "NOAPLICA"		              => "&lt;No aplica&gt;",
    "PROVEEDOR" 	              => "Proveedor",
    "MARCA"                       => "Marca",
    "ARTICULO"                    => "Grupo",
    "ASCENDENTE"	              => "Ascendente",
    "DESCENDENTE"                 => "Descendente",
    "FECHA"		                  => "Fecha",
    "IMRPIMIR_PDF"	              => "Imprimir",
    "ERROR_DATOS_INCOMPLETOS"     => "Hace falta información",
    "PESTANA_DATOS_TECNICOS"      => "Datos técnicos",
    "SIEMPRE_IMPRIME"	          => "Imprimir siempre",
    "OCASIONALMENTE_IMPRIME"      => "Imprimir solo cuando hay existencias",
    "NUNCA_IMPRIME"	              => "Imprimir Nunca",
    "ESTADO_IMPRESION"            => "Imprime",
    "SELECCIONAR_TODOS"           => "Seleccionar todos",
    "DESELECCIONAR_TODOS"         => "Deseleccionar todos",
    "DETALLE_KARDEX"              => "Detalle kardex",
    "AYUDA_DETALLE_KARDEX"        => "Es el detalle del kardex",
    "AYUDA_TIPO_ARTICULO"         => "Tipo de articulo",
    "AYUDA_REFERENCIA_PROVEEDOR"  => "Digite el código o referencia del articulo del proveedor",
    "AYUDA_MARCA"                 => "Marca del articulo",
    "AYUDA_MANEJO_INVENTARIO"     => "Manejo de inventario",
    "AYUDA_UNIDAD_VENTA"          => "Unidad de venta",
    "AYUDA_UNIDAD_COMPRA"         => "Unidad de compra",
    "AYUDA_UNIDAD_PRESENTACION"   => "Unidad de presentación",
    "AYUDA_PAIS"                  => "Pais de procedencia",
    "AYUDA_ESTADO"                => "Estado del articuo",
    "CODIGO_VACIO"				  => "Debe ingresar el código del articulo",
    "DESCRIPCION_VACIO"			  => "Debe ingresar la descripción",
    "REFERENCIA_VACIO"		 	  => "Debe seleccionar la referencia",
    "UNIDAD_VENTA_VACIO"		  => "Debe seleccionar la unidad de venta",
    "UNIDAD_COMPRA_VACIO"		  => "Debe seleccionar la unidad de compra",
    "UNIDAD_PRESENTACION_VACIO"	  => "Debe seleccionar la unidad de presentación",
    "PROVEEDOR_VACIO"			  => "Debe ingresar el proveedor",
    "ERROR_PREFERENCIAS_USUARIO"  => "Ingrese las preferencias por usuario:Tipo Articulo, Unid Compra, Unid Presentación",
    "ERROR_PREFERENCIAS_GLOBALES" => "Ingrese las preferencias por empresa:Impuesto Compra, Impuesto Venta",
    "ERROR_UNIDADES"              => "No hay unidades de medida creadas, debe crear por lo menos una unidad de medida",
    "SIN_REGISTROS_TABLAS"        => "No existen registros en las siguientes tablas:\n",
    "CREAR_TASA"                  => "-Tasas\n",
    "CREAR_PROVEEDOR"             => "-Proveedores\n",
    "CREAR_MARCA"                 => "-Marcas\n",
    "CREAR_ESTRUCTURA"            => "-Estructura grupos\n",
    "CREAR_UNIDAD"                => "-Unidades\n",
    "CREAR_PAISES"                => "-Paises\n",
    "CREAR_REGISTROS"             => "\nDebe crear por lo menos un registro para cada tabla",
    "PESTANA_REFERENCIA"          => "Referencias alternas",
    "PRINCIPAL"                   => "Referencia principal",
    "AYUDA_PRINCIPAL"             => "Marque esta casilla si es la referencia principal del articulo",
    "EXISTE_REFERENCIA"           => "La referencia ya existe, verifique!!!",
    "EXISTE_REFERENCIA_CODIGO"    => "El proveedor ya tiene asignada la referencia para otro código",
    "EXISTE_REFERENCIA_PRINCIPAL" => "Ya hay una referencia principal en la tabla",
    "REFERENCIA_ELIMINADA"        => "Referencia alterna eliminada",
    "ERROR_ELIMINAR_REFERENCIA"   => "No se pudo eliminar la referencia alterna, Vefifique!!!",
    "DIGITE_REFRENCIA"            => "Debe digitar la referencia",
    "CODIGO_ALFANUMERICO_VACIO"   => "Debe digitar en la pestaña general el código o referencia principal del articulo del proveedor",
    "REFERENCIA_DIFERENTE"        => "La referencia alterna debe ser diferente al código o referencia principal del proveedor",
    "ESTRUCTURA_VACIO"            => "Debe seleccionar la estructura de grupo"
);
?>
