REPLACE INTO job_actividades_economicas_dian VALUES
(10, "Asalariados"),
(90, "Rentistas de capital. Solo para personas naturales"),
(111, "Producción especializada del café"),
(112, "Producción especializada de flor de corte bajo cubierta y al aire libre"),
(113, "Producción especializada de banano"),
(114, "Producción especializada de caña de azúcar"),
(115, "Producción especializada de cereales y oleaginosas"),
(116, "Producción especializada de hortalizas y legumbres"),
(117, "Producción especializada de frutas, nueces, plantas bebestibles y especias"),
(118, "Producción agrícola ncp en unidades especializadas"),
(119, "Producción agrícola en unidades no especializadas"),
(121, "Cría especializada de ganado vacuno"),
(122, "Cría especializada de ganado porcino"),
(123, "Cría especializada de aves de corral"),
(124, "Cría especializada de ovejas, cabras, caballos, asnos, mulas y burdéganos"),
(125, "Cría especializada de otros animales ncp y la obtención de sus productos"),
(129, "Actividad pecuaria no especializada"),
(130, "Actividad mixta (agrícola y pecuaria)"),
(140, "Actividades de servicios, agrícolas y ganaderos, excepto las actividades veterinarias"),
(150, "Caza ordinaria y mediante trampas y repoblación de animales de caza, incluso actividades de servici"),
(201, "Silvicultura y explotación de la madera"),
(202, "Actividades de servicios relacionadas con la silvicultura y la extracción de la madera"),
(501, "Pesca y cultivo de peces en criaderos y granjas piscícolas"),
(502, "Actividades de servicios relacionados con la pesca"),
(1010, "Extracción y aglomeración de hulla (carbón de piedra)"),
(1020, "Extracción y aglomeración de carbón lignítico"),
(1030, "Extracción y aglomeración de turba"),
(1110, "Extracción de petróleo crudo y de gas natural"),
(1120, "Actividades de servicios relacionadas con la extracción de petróleo y gas, excepto las actividades "),
(1200, "Extracción de minerales de uranio y de torio"),
(1310, "Extracción del mineral de hierro"),
(1320, "Extracción de metales preciosos"),
(1331, "Extracción de minerales de níquel"),
(1339, "Extracción de otros minerales metalíferos no ferrosos, excepto níquel"),
(1411, "Extracción de piedra, arena y arcillas comunes"),
(1412, "Extracción de yeso y anhidrita"),
(1413, "Extracción de caolín, arcillas de uso industrial y bentonitas"),
(1414, "Extracción de arenas y gravas silíceas"),
(1415, "Extracción de caliza y dolomita"),
(1421, "Extracción de minerales para la fabricación de abonos y productos químicos"),
(1422, "Extracción de halita (sal)"),
(1431, "Extracción de esmeraldas"),
(1432, "Extracción de otras piedras preciosas y semipreciosas"),
(1490, "Extracción de otros minerales no metálicos ncp"),
(1511, "Producción, transformación y conservación de carne y de derivados cárnicos"),
(1512, "Transformación y conservación de pescado y de derivados del pescado"),
(1521, "Elaboración de alimentos compuestos principalmente de frutas, legumbres y hortalizas"),
(1522, "Elaboración de aceites y grasas de origen vegetal y animal"),
(1530, "Elaboración de productos lácteos"),
(1541, "Elaboración de productos de molinería"),
(1542, "Elaboración de almidones y de productos derivados del almidón"),
(1543, "Elaboración de alimentos preparados para animales"),
(1551, "Elaboración de productos de panadería"),
(1552, "Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares"),
(1561, "Trilla de café"),
(1562, "Descafeinado"),
(1563, "Tostión y molienda del café"),
(1564, "Elaboración de otros derivados del café"),
(1571, "Fabricación y refinación de azúcar"),
(1572, "Fabricación de panela"),
(1581, "Elaboración de cacao, chocolate y productos de confitería"),
(1589, "Elaboración de otros productos alimenticios ncp"),
(1591, "Destilación, rectificación y mezcla de bebidas alcohólicas"),
(1592, "Elaboración de bebidas fermentadas no destiladas"),
(1593, "Producción de malta, elaboración de cervezas y otras bebidas malteadas"),
(1594, "Elaboración de bebidas no alcohólicas"),
(1600, "Fabricación de productos de tabaco"),
(1710, "Preparación e hilatura de fibras textiles"),
(1720, "Tejedura de productos textiles"),
(1730, "Acabado de productos textiles no producidos en la misma unidad de producción"),
(1741, "Confección de artículos con materiales textiles no producidos en la misma unidad, excepto prendas d"),
(1742, "Fabricación de tapices y alfombras para pisos"),
(1743, "Fabricación de cuerdas, cordeles, cables, bramantes y redes"),
(1749, "Fabricación de otros artículos textiles ncp"),
(1750, "Fabricación de tejidos y artículos de punto y ganchillo"),
(1810, "Fabricación de prendas de vestir, excepto prendas de piel"),
(1820, "Preparado y teñido de pieles"),
(1910, "Curtido y preparado de cueros"),
(1921, "Fabricación de calzado de cuero y piel"),
(1922, "Fabricación de calzado de materiales textiles"),
(1923, "Fabricación de calzado de caucho excepto el calzado deportivo"),
(1924, "Fabricación de calzado de plástico excepto el calzado deportivo"),
(1925, "Fabricación de calzado deportivo, excepto el moldeado"),
(1926, "Fabricación de partes de calzado"),
(1929, "Fabricación de calzado ncp"),
(1931, "Fabricación de artículos de viaje, bolsos de mano, y artículos similares elaborados en cuero"),
(1932, "Fabricación de artículos de viaje, bolsos de mano y artículos similares, elaborados en materiales s"),
(1939, "Fabricación de artículos de viaje, bolsos de mano, y artículos similares elaborados con materiales "),
(2004, "Derechos Reservados DIAN"),
(2010, "Aserrado, acepillado e impregnación de la madera"),
(2020, "Fabricación de hojas de madera para enchapado"),
(2030, "Fabricación de partes y piezas de carpintería para edificios y construcción"),
(2040, "Fabricación de recipientes de madera"),
(2090, "Fabricación de otros productos de madera"),
(2101, "Fabricación de pastas celulósicas"),
(2102, "Fabricación de papel y cartón ondulado, fabricación de envases, empaques y de embalajes de papel y "),
(2109, "Fabricación de otros artículos de papel y cartón"),
(2211, "Edición de libros, folletos, partituras y otras publicaciones"),
(2212, "Edición de periódicos, revistas y publicaciones periódicas"),
(2213, "Edición de materiales grabados"),
(2219, "Otros trabajos de edición"),
(2220, "Actividades de impresión"),
(2231, "Arte, diseño y composición"),
(2232, "Fotomecánica y análogos"),
(2233, "Encuadernación"),
(2234, "Acabado o recubrimiento"),
(2239, "Otros servicios conexos ncp"),
(2240, "Reproducción de materiales grabados"),
(2310, "Fabricación de productos de hornos de coque"),
(2321, "Fabricación de productos de la refinación del petróleo, elaborados en refinería"),
(2322, "Elaboración de productos derivados del petróleo, fuera de refinería"),
(2330, "Elaboración de combustible nuclear"),
(2411, "Fabricación de sustancias químicas básicas, excepto abonos y compuestos inorgánicos nitrogenados"),
(2412, "Fabricación de abonos y compuestos inorgánicos nitrogenados"),
(2413, "Fabricación de plásticos en formas primarias"),
(2414, "Fabricación de caucho sintético en formas primarias"),
(2421, "Fabricación de plaguicidas y otros productos químicos de uso agropecuario"),
(2422, "Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas"),
(2423, "Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos"),
(2424, "Fabricación de jabones y detergentes, preparados para limpiar y pulir"),
(2429, "Fabricación de otros productos químicos ncp"),
(2430, "Fabricación de fibras sintéticas y artificiales"),
(2511, "Fabricación de llantas y neumáticos de caucho"),
(2512, "Reencauche de llantas usadas"),
(2513, "Fabricación de formas básicas de caucho"),
(2519, "Fabricación de otros productos de caucho ncp"),
(2521, "Fabricación de formas básicas de plástico"),
(2529, "Fabricación de artículos de plástico ncp"),
(2610, "Fabricación de vidrio y de productos de vidrio"),
(2691, "Fabricación de productos de cerámica no refractaria, para uso no estructural"),
(2692, "Fabricación de productos de cerámica refractaria"),
(2693, "Fabricación de productos de arcilla y cerámica no refractaria, para uso estructural"),
(2694, "Fabricación de cemento, cal y yeso"),
(2695, "Fabricación de artículos de hormigón, cemento y yeso"),
(2696, "Corte, tallado y acabado de la piedra"),
(2699, "Fabricación de otros productos minerales no metálicos ncp"),
(2710, "Industrias básicas de hierro y de acero"),
(2721, "Industrias básicas de metales preciosos"),
(2729, "Industrias básicas de otros metales no ferrosos"),
(2731, "Fundición de hierro y de acero"),
(2732, "Fundición de metales no ferrosos"),
(2811, "Fabricación de productos metálicos para uso estructural"),
(2812, "Fabricación de tanques, depósitos y recipientes de metal"),
(2813, "Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central"),
(2891, "Forja, prensado, estampado y laminado de metal"),
(2892, "Tratamiento y revestimiento de metales"),
(2893, "Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería"),
(2899, "Fabricación de otros productos elaborados de metal ncp"),
(2911, "Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicl"),
(2912, "Fabricación de bombas, compresores, grifos y válvulas"),
(2913, "Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión"),
(2914, "Fabricación de hornos, hogares y quemadores industriales"),
(2915, "Fabricación de equipo de elevación y manipulación"),
(2919, "Fabricación de otros tipos de maquinaria de uso general ncp"),
(2921, "Fabricación de maquinaria agropecuaria y forestal"),
(2922, "Fabricación de máquinas herramienta"),
(2923, "Fabricación de maquinaria para la metalurgia"),
(2924, "Fabricación de maquinaria para la explotación de minas y canteras y para la construcción"),
(2925, "Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco"),
(2926, "Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros"),
(2927, "Fabricación de armas y municiones"),
(2929, "Fabricación de otros tipos de maquinaria de uso especial ncp"),
(2930, "Fabricación de aparatos de uso doméstico ncp"),
(3000, "Fabricación de maquinaria de oficina, contabilidad e informática"),
(3110, "Fabricación de motores, generadores y transformadores"),
(3120, "Fabricación de aparatos de distribución y control de la energía eléctrica"),
(3130, "Fabricación de hilos y cables aislados"),
(3140, "Fabricación de acumuladores y de pilas eléctricas"),
(3150, "Fabricación de lámparas eléctricas y equipo de iluminación"),
(3190, "Fabricación de otros tipos de equipo eléctrico ncp"),
(3210, "Fabricación de tubos y válvulas electrónicas y de otros componentes electrónicos"),
(3220, "Fabricación de transmisores de radio y televisión y de aparatos para telefonía y telegrafía"),
(3230, "Fabricación de receptores de radio y televisión, de aparatos de grabación de reproducción del soni"),
(3311, "Fabricación de equipo médico y quirúrgico y de aparatos ortésicos y protésicos"),
(3312, "Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y otros fines, excep"),
(3313, "Fabricación de equipo de control de procesos industriales"),
(3320, "Fabricación de instrumentos ópticos y de equipo fotográfico"),
(3330, "Fabricación de relojes"),
(3410, "Fabricación de vehículos automotores y sus motores"),
(3420, "Fabricación de carrocerías para vehículos automotores"),
(3430, "Fabricación de partes, piezas y accesorios (autopartes) para vehículos automotores y para sus motor"),
(3511, "Construcción y reparación de buques"),
(3512, "Construcción y reparación de embarcaciones de recreo y de deporte"),
(3520, "Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías"),
(3530, "Fabricación de aeronaves y de naves espaciales"),
(3591, "Fabricación de motocicletas"),
(3592, "Fabricación de bicicletas y de sillones de ruedas para discapacitados"),
(3599, "Fabricación de otros tipos de equipo de transporte ncp"),
(3611, "Fabricación de muebles para el hogar"),
(3612, "Fabricación de muebles para oficina"),
(3613, "Fabricación de muebles para comercio y servicios"),
(3614, "Fabricación de colchones y somieres"),
(3619, "Fabricación de otros muebles ncp"),
(3691, "Fabricación de joyas y de artículos conexos"),
(3692, "Fabricación de instrumentos musicales"),
(3693, "Fabricación de artículos deportivos"),
(3694, "Fabricación de juegos y juguetes"),
(3699, "Otras industrias manufactureras ncp"),
(3710, "Reciclaje de desperdicios y de desechos metálicos"),
(3720, "Reciclaje de desperdicios y desechos no metálicos"),
(4010, "Generación, captación y distribución de energía eléctrica"),
(4020, "Fabricación de gas"),
(4030, "Suministro de vapor y agua caliente"),
(4100, "Captación, depuración y distribución de agua"),
(4511, "Trabajos de demolición y preparación de terrenos para la construcción de edificaciones"),
(4512, "Trabajos de preparación de terrenos para obras civiles"),
(4521, "Construcción de edificaciones para uso residencial"),
(4522, "Construcción de edificaciones para uso no residencial"),
(4530, "Construcción de obras de ingeniería civil"),
(4541, "Instalaciones hidráulicas y trabajos conexos"),
(4542, "Trabajos de electricidad"),
(4543, "Trabajos de instalación de equipos"),
(4549, "Otros trabajos de acondicionamiento"),
(4551, "Ornamentación e Instalación de vidrios y ventanas"),
(4552, "Trabajos de pintura y terminación de muros y pisos"),
(4559, "Otros trabajos de terminación y acabado"),
(4560, "Alquiler de equipo para construcción y demolición dotado de operarios"),
(5011, "Comercio de vehículos automotores nuevos"),
(5012, "Comercio de vehículos automotores usados"),
(5020, "Mantenimiento y reparación de vehículos automotores"),
(5030, "Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores"),
(5040, "Comercio, mantenimiento y reparación de motocicletas y de sus partes, piezas y accesorios"),
(5051, "Comercio al por menor de combustible para automotores"),
(5052, "Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehíc"),
(5111, "Comercio al por mayor a cambio de una retribución o por contrata de productos agrícolas (excepto ca"),
(5112, "Comercio al por mayor a cambio de una retribución o por contrata de café pergamino"),
(5113, "Comercio al por mayor a cambio de una retribución o por contrata de productos manufacturados"),
(5119, "Comercio al por mayor a cambio de una retribución o por contrata de productos ncp"),
(5121, "Comercio al por mayor de materias primas, productos agrícolas, excepto café y flores"),
(5122, "Comercio al por mayor de café pergamino"),
(5123, "Comercio al por mayor de flores y plantas ornamentales"),
(5124, "Comercio al por mayor de materias primas pecuarias, animales vivos"),
(5125, "Comercio al por mayor de productos alimenticios, excepto café trillado"),
(5126, "Comercio al por mayor de café trillado"),
(5127, "Comercio al por mayor de bebidas y productos del tabaco"),
(5131, "Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico"),
(5132, "Comercio al por mayor de prendas de vestir, accesorios de prendas de vestir y artículos elaborados "),
(5133, "Comercio al por mayor de calzado"),
(5134, "Comercio al por mayor de aparatos, artículos y equipo de uso doméstico"),
(5135, "Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador"),
(5136, "Comercio al por mayor de equipos médicos quirúrgicos y de aparatos ortésicos y protésicos"),
(5137, "Comercio al por mayor de papel y cartón"),
(5139, "Comercio al por mayor de otros productos de consumo ncp"),
(5141, "Comercio al por mayor de materiales de construcción, ferretería y vidrio"),
(5142, "Comercio al por mayor de pinturas y productos conexos"),
(5151, "Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos"),
(5152, "Comercio al por mayor de metales y minerales metalíferos en formas primarias"),
(5153, "Comercio al por mayor de productos químicos básicos, plásticos y caucho en formas primarias y produ"),
(5154, "Comercio al por mayor de fibras textiles"),
(5155, "Comercio al por mayor de desperdicios o desechos industriales y material para reciclaje"),
(5159, "Comercio al por mayor de otros productos intermedios ncp"),
(5161, "Comercio al por mayor de maquinaria y equipo para la agricultura, minería, construcción y la indust"),
(5162, "Comercio al por mayor de equipo de transporte, excepto vehículos automotores y motocicletas"),
(5163, "Comercio al por mayor de maquinaria para oficina, contabilidad e informática"),
(5169, "Comercio al por mayor de maquinaria y equipo ncp"),
(5170, "Mantenimiento y reparación de maquinaria y equipo"),
(5190, "Comercio al por mayor de productos diversos ncp"),
(5211, "Comercio al por menor, en establecimientos no especializados, con surtido compuesto principalmente "),
(5219, "Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente po"),
(5221, "Comercio al por menor de frutas y verduras, en establecimientos especializados"),
(5222, "Comercio al por menor de leche, productos lácteos y huevos en establecimientos especializados"),
(5223, "Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos "),
(5224, "Comercio al por menor de productos de confitería en establecimientos especializados"),
(5225, "Comercio al por menor de bebidas y productos del tabaco en establecimientos especializados"),
(5229, "Comercio al por menor de otros productos alimenticios ncp, en establecimientos especializados"),
(5231, "Comercio al por menor de productos farmacéuticos, medicinales, y odontológicos"),
(5232, "Comercio al por menor de productos textiles en establecimientos especializados"),
(5233, "Comercio al por menor de prendas de vestir y sus accesorios"),
(5234, "Comercio al por menor de todo tipo de calzado, artículos de cuero y sucedáneos del cuero, en establ"),
(5235, "Comercio al por menor de electrodomésticos, en establecimientos especializados"),
(5236, "Comercio al por menor de muebles para el hogar, en establecimientos especializados"),
(5237, "Comercio al por menor de equipos y artículos de uso doméstico diferentes de electrodomésticos y mue"),
(5239, "Comercio al por menor de productos diversos ncp, en establecimientos especializados"),
(5241, "Comercio al por menor de artículos de ferretería, cerrajería y productos de vidrio, excepto pintura"),
(5242, "Comercio al por menor pinturas en establecimientos especializados"),
(5243, "Comercio al por menor de muebles para oficina, maquinaria y equipo de oficina, computadores y progr"),
(5244, "Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en e"),
(5245, "Comercio al por menor de equipo fotográfico, en establecimientos especializados"),
(5246, "Comercio al por menor de equipo óptico y de precisión, en establecimientos especializados"),
(5249, "Comercio al por menor de otros nuevos productos de consumo ncp en establecimientos especializados"),
(5251, "Comercio al por menor de artículos usados en establecimientos especializados"),
(5252, "Actividades comerciales de las casas de empeño o compraventas"),
(5261, "Comercio al por menor a través de casas de venta por correo"),
(5262, "Comercio al por menor en puestos móviles"),
(5269, "Otros tipos de comercio al por menor no realizado en establecimientos"),
(5271, "Reparación de efectos personales"),
(5272, "Reparación de enseres domésticos"),
(5511, "Alojamiento en hoteles, hostales y apartahoteles"),
(5512, "Alojamiento en residencias, moteles y amoblados"),
(5513, "Alojamiento en centros vacacionales y zonas de camping"),
(5519, "Otros tipos de alojamiento ncp"),
(5521, "Expendio a la mesa de comidas preparadas, en restaurantes"),
(5522, "Expendio, a la mesa, de comidas preparadas en cafeterías"),
(5523, "Expendio, por autoservicio, de comidas preparadas en restaurantes"),
(5524, "Expendio, por autoservicio, de comidas preparadas en cafeterías"),
(5529, "Otros tipos de expendio ncp de alimentos preparados"),
(5530, "Expendio de bebidas alcohólicas para el consumo dentro del establecimiento"),
(6010, "Transporte por vía férrea"),
(6021, "Transporte urbano colectivo regular de pasajeros"),
(6022, "Transporte intermunicipal colectivo regular de pasajeros"),
(6023, "Transporte internacional colectivo regular de pasajeros"),
(6031, "Transporte no regular individual de pasajeros"),
(6032, "Transporte colectivo no regular de pasajeros"),
(6039, "Otros tipos de transporte no regular de pasajeros ncp"),
(6041, "Transporte municipal de carga por carretera"),
(6042, "Transporte intermunicipal de carga por carretera"),
(6043, "Transporte internacional de carga por carretera"),
(6044, "Alquiler de vehículos de carga con conductor"),
(6050, "Transporte por tuberías"),
(6111, "Transporte marítimo internacional"),
(6112, "Transporte marítimo de cabotaje"),
(6120, "Transporte fluvial"),
(6211, "Transporte regular nacional de pasajeros por vía aérea"),
(6212, "Transporte regular nacional de carga por vía aérea"),
(6213, "Transporte regular internacional de pasajeros, por vía aérea"),
(6214, "Transporte regular internacional de carga, por vía aérea"),
(6220, "Transporte no regular, por vía aérea"),
(6310, "Manipulación de carga"),
(6320, "Almacenamiento y depósito"),
(6331, "Actividades de estaciones de transporte terrestre"),
(6332, "Actividades de estaciones de transporte acuático"),
(6333, "Actividades de aeropuertos"),
(6339, "Otras actividades complementarias del transporte"),
(6340, "Actividades de agencias de viajes y organizadores de viajes"),
(6390, "Actividades de otras agencias de transporte"),
(6411, "Actividades postales nacionales"),
(6412, "Actividades de correo distintas de las actividades postales nacionales"),
(6421, "Servicios telefónicos"),
(6422, "Servicios de transmisión de datos a través de redes"),
(6423, "Servicios de transmisión de programas de radio y televisión"),
(6424, "Servicios de transmisión por cable"),
(6425, "Otros servicios de telecomunicaciones"),
(6426, "Servicios relacionados con las telecomunicaciones"),
(6511, "Banca central"),
(6512, "Actividades de los bancos diferentes del Banco Central"),
(6513, "Actividades de las corporaciones d ahorro y vivienda"),
(6514, "Actividades de las corporaciones financieras"),
(6515, "Actividades de las compañías de financiamiento comercial"),
(6516, "Actividades de las cooperativas de grado superior de carácter financiero"),
(6519, "Otros tipos de intermediación monetaria ncp"),
(6591, "Arrendamiento financiero (leasing)"),
(6592, "Actividades de las sociedades de fiducia"),
(6593, "Actividades de las cooperativas financieras y fondos de empleados"),
(6594, "Actividades de las sociedades de capitalización"),
(6595, "Actividades de compra de cartera (factoring)"),
(6596, "Otros tipos de crédito"),
(6599, "Otros tipos de intermediación financiera ncp"),
(6601, "Planes de seguros generales"),
(6602, "Planes de seguros de vida"),
(6603, "Planes de reaseguros"),
(6604, "Planes de pensiones y cesantías"),
(6711, "Administración de mercados financieros"),
(6712, "Actividades de las bolsas de valores"),
(6713, "Actividades de comisionistas y corredores de valores"),
(6714, "Otras actividades relacionadas con el mercado de valores"),
(6715, "Actividades de las casas de cambio"),
(6719, "Actividades auxiliares de la administración financiera ncp"),
(6721, "Actividades auxiliares de los seguros"),
(6722, "Actividades auxiliares de los fondos de pensiones y cesantías"),
(7010, "Actividades inmobiliarias realizadas con bienes propios o arrendados"),
(7020, "Actividades inmobiliarias realizadas a cambio de una retribución o por contrata"),
(7111, "Alquiler de equipo de transporte terrestre"),
(7112, "Alquiler de equipo de transporte acuático"),
(7113, "Alquiler de equipo de transporte aéreo"),
(7121, "Alquiler de maquinaria y equipo agropecuario"),
(7122, "Alquiler de maquinaria y equipo de construcción y de ingeniería civil"),
(7123, "Alquiler de maquinaria y equipo de oficina (incluso computadoras)"),
(7129, "Alquiler de otros tipos de maquinaria y equipo ncp"),
(7130, "Alquiler de efectos personales y enseres domésticos ncp"),
(7210, "Consultores en equipo de informática"),
(7220, "Consultores en programas de informática y suministro de programas de informática"),
(7230, "Procesamiento de datos"),
(7240, "Actividades relacionadas con bases de datos"),
(7250, "Mantenimiento y reparación de maquinaria de oficina, contabilidad e informática"),
(7290, "Otras actividades de informática"),
(7310, "Investigación y desarrollo experimental en el campo de las ciencias naturales y la ingeniería"),
(7320, "Investigación y desarrollo experimental en el campo de las ciencias sociales"),
(7411, "Actividades jurídicas"),
(7412, "Actividades de contabilidad, teneduría de libros y auditoría"),
(7413, "Investigación de mercados y realización de encuestas de opinión pública"),
(7414, "Actividades de asesoramiento empresarial y en materia de gestión"),
(7421, "Actividades de arquitectura e ingeniería y actividades conexas de asesoramiento técnico"),
(7422, "Ensayos y análisis técnicos"),
(7430, "Publicidad"),
(7491, "Obtención y suministro de personal"),
(7492, "Actividades de investigación y seguridad"),
(7493, "Actividades de limpieza de edificios"),
(7494, "Actividades de fotografía"),
(7495, "Actividades de envase y empaque"),
(7499, "Otras actividades empresariales ncp"),
(7511, "Actividades legislativas de la administración pública en general"),
(7512, "Actividades ejecutivas de la administración pública en general"),
(7513, "Regulación de las actividades de organismos que prestan servicios de salud"),
(7514, "Actividades reguladoras y facilitadoras de la actividad económica"),
(7515, "Actividades auxiliares de servicios para la administración pública en general"),
(7521, "Relaciones exteriores"),
(7522, "Actividades de defensa"),
(7523, "Actividades de la justicia"),
(7524, "Actividades de la policía y protección civil"),
(7530, "Actividades de seguridad social de afiliación obligatoria"),
(8011, "Educación preescolar"),
(8012, "Educación básica primaria"),
(8021, "Educación básica secundaria"),
(8022, "Educación media"),
(8030, "Servicio de educación laboral especial"),
(8041, "Establecimientos que prestan el servicio de educación preescolar y básica primaria"),
(8042, "Establecimientos que prestan el servicio de educación preescolar y básica (básica primaria y básica"),
(8043, "Establecimientos que prestan el servicio de educación preescolar,"),
(8044, "Establecimientos que prestan el servicio de educación (básica primaria y básica secundaria)"),
(8045, "Establecimientos que prestan el servicio de educación (básica primaria y básica secundaria) y media"),
(8046, "Establecimientos que prestan el servicio de educación básica secundaria y media"),
(8050, "Educación superior"),
(8060, "Educación no formal"),
(8511, "Actividades de las instituciones prestadoras de servicios de salud, con internación"),
(8512, "Actividades de la practica médica"),
(8513, "Actividades de la practica odontológica"),
(8514, "Actividades de apoyo diagnóstico"),
(8515, "Actividades de apoyo terapéutico"),
(8519, "Otras actividades relacionadas con la salud humana"),
(8520, "Actividades veterinarias"),
(8531, "Servicios sociales con alojamiento"),
(8532, "Servicios sociales sin alojamiento"),
(9000, "Eliminación de desperdicios y aguas residuales, saneamiento y actividades similares"),
(9111, "Actividades de organizaciones empresariales y de empleadores"),
(9112, "Actividades de organizaciones profesionales"),
(9120, "Actividades de sindicatos"),
(9191, "Actividades de organizaciones religiosas"),
(9192, "Actividades de organizaciones políticas"),
(9199, "Actividades de otras organizaciones ncp"),
(9211, "Producción y distribución de filmes y videocintas"),
(9212, "Exhibición de filmes y videocintas"),
(9213, "Actividades de radio y televisión"),
(9214, "Actividades teatrales y musicales y otras actividades artísticas"),
(9219, "Otras actividades de entretenimiento ncp"),
(9220, "Actividades de agencias de noticias"),
(9231, "Actividades de bibliotecas y archivos"),
(9232, "Actividades de museos y preservación de lugares y edificios históricos"),
(9233, "Actividades de jardines botánicos y zoológicos y de parques nacionales"),
(9241, "Actividades deportivas"),
(9242, "Actividades de juegos de azar"),
(9249, "Otras actividades de esparcimiento"),
(9301, "Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco"),
(9302, "Peluquería y otros tratamientos de belleza"),
(9303, "Pompas fúnebres y actividades conexas"),
(9309, "Otras actividades de servicios ncp"),
(9500, "Hogares privados con servicio doméstico"),
(9900, "Organizaciones y órganos extraterritoriales");
