<?php

/**
*
* Copyright (C) 2008 Felinux Ltda
* Raul Mauricio Oidor Lozano <ozzymauricio75@gmail.com>
*
* Este archivo es parte de:
* Jobdaily:: Sofware empresarial a la medida
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los términos de la Licencia Pública General GNU
* publicada por la Fundación para el Software Libre, ya sea la versión 3
* de la Licencia, o (a su elección) cualquier versión posterior.
*
* Este programa se distribuye con la esperanza de que sea útil, pero
* SIN GARANTÍA ALGUNA; ni siquiera la garantía implícita MERCANTIL o
* de APTITUD PARA UN PROPÓSITO DETERMINADO. Consulte los detalles de
* la Licencia Pública General GNU para obtener una información más
* detallada.
*
* Debería haber recibido una copia de la Licencia Pública General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(
    "GESTEMPR"                           => "Empresas",
    "ADICEMPR"                           => "Adicionar empresas",
    "CONSEMPR"                           => "Consultar empresas",
    "MODIEMPR"                           => "Modificar empresas",
    "ELIMEMPR"                           => "Eliminar empresas",
    "ID"                                 => "Consecutivo base datos",
    "CODIGO"                             => "Código interno",
    "CODIGO_EMPRESA"                     => "Código",
    "RAZON_SOCIAL"                       => "Razón social",
    "NOMBRE_CORTO"                       => "Nombre corto",
    "FECHA_CIERRE"                       => "Fecha cierre",
    "ACTIVO"                             => "Estado",
    "CODIGO_TERCERO"                     => "Código tercero",
    "TERCERO"                            => "Documento tercero",
    "NOMBRE_COMPLETO"                    => "Nombre",
    "REGIMEN"                            => "Régimen",
    "GRAN_CONTRIBUYENTE"                 => "Gran contribuyente",
    "RETENEDOR_FUENTE"                   => "Retenedor fuente",
    "RESOLUCION_RETEFUENTE"              => "Resolución retefuente",
    "RETENEDOR_ICA"                      => "Retenedor ica",
    "ACTIVIDAD_PRINCIPAL"                => "Actividad económica principal",
    "ACTIVIDAD_SECUNDARIA"               => "Actividad económica secundaria",
    "PAIS"                               => "País",
    "DEPARTAMENTO"                       => "Departamento",
    "MUNICIPIO"                          => "Municipio expedición",
    "DOCUMENTO_TERCERO"                  => "Documento de identidad",
    "TIPO_PERSONA"                       => "Tipo de persona",
    "PERSONA_NATURAL"                    => "Persona natural",
    "PERSONA_JURIDICA"                   => "Persona juridica",
    "CODIGO_INTERNO"                     => "Codigo interno",
    "NATURAL"                            => "Natural",
    "JURIDICA"                           => "Juridica",
    "INTERNO"                            => "Codigo interno",
    "NATURAL_COMERCIANTE"                => "Natural Comerciante",
    "DIGITO_VERIFICACION"                => "Digito de verificación",
    "TIPO_DOCUMENTO_IDENTIDAD"           => "Tipo de documento de identidad",
    "PRIMER_NOMBRE"                      => "Primer nombre",
    "SEGUNDO_NOMBRE"                     => "Segundo nombre",
    "PRIMER_APELLIDO"                    => "Primer apellido",
    "SEGUNDO_APELLIDO"                   => "Segundo apellido",
    "DATO_VACIO"                         => "",
    "NOMBRE_COMERCIAL"                   => "Nombre comercial",
    "RETIENE_FUENTE"                     => "Retiene fuente",
    "AUTORETENEDOR"                      => "Autoretenedor en la fuente",
    "RETIENE_IVA"                        => "Retiene IVA",
    "RETIENE_ICA"                        => "Retiene ICA",
    "RETENEDOR_ICA"                      => "Autoretenedor ICA",
    "LOCALIDAD"                          => "Barrio o corregimiento",
    "DIRECCION"                          => "Direccion",
    "TELEFONO_PRINCIPAL"                 => "Telefono principal",
    "FAX"                                => "Fax",
    "CELULAR"                            => "Celular",
    "CORREO"                             => "Correo electronico",
    "SITIO_WEB"                          => "Pagina de internet(Web)",
    "NATURAL"                            => "Natural",
    "JURIDICA"                           => "Jurídica",
    "INTERNO"                            => "Código interno",
    "PESTANA_GENERAL"                    => "General",
    "PESTANA_TRIBUTARIA"                 => "Tributaria",
    "PESTANA_TERCERO"                    => "Básica",
    "PESTANA_UBICACION_TERCERO"          => "Ubicación",
    "ESTADO_ACTIVA"                      => "Activa",
    "ESTADO_INACTIVA"                    => "Inactiva",
    "ESTADO_INACTIVA_GENERA"             => "Inactiva genera",
    "REGIMEN_SIMPLIFICADO"               => "Simplificado",
    "REGIMEN_COMUN"                      => "Común",
    "NO"                                 => "No",
    "SI"                                 => "Si",
    "RESOLUCION_RETEIVA"                 => "Resolución retiene IVA",
    "RESOLUCION_RETEICA"                 => "Resolución retiene ICA",
    "RESOLUCION_CONTRIBUYENTE"           => "Resolución gran contribuyente",
    "AYUDA_TERCEROS"                     => "Tercero al que pertenece la empresa",
    "AYUDA_CODIGO"                       => "Código de la empresa",
    "AYUDA_ACTIVO"                       => "Estado actual de la empresa activa-inactiva",
    "AYUDA_RAZON_SOCIAL"                 => "Razón social o nombre de la empresa",
    "AYUDA_NOMBRE_CORTO"                 => "Nombre corto de la empresa",
    "AYUDA_FECHA_CIERRE"                 => "Fecha de cierre de la empresa",
    "AYUDA_REGIMEN"                      => "Tipo de régimen de la empresa",
    "AYUDA_GRAN_CONTRIBUYENTE"           => "La empresa es gran contribuyente o no",
    "AYUDA_ACTIVIDAD_PRINCIPAL"          => "Actividad económica principal a la cual se dedica la empresa",
    "AYUDA_ACTIVIDAD_SECUNDARIA"         => "Actividad económica secundaria a la cual se dedica la empresa",
    "AYUDA_TERCERO"                      => "Digite el numero del documento de identidad",
    "AYUDA_TIPO_PERSONA"                 => "Tipo de persona al que petenece",
    "AYUDA_DOCUMENTO"                    => "Seleccione el tipo de documento de identidad",
    "AYUDA_PRIMER_NOMBRE"                => "Digite el primer nombre",
    "AYUDA_SEGUNDO_NOMBRE"               => "Digite el segundo nombre",
    "AYUDA_PRIMER_APELLIDO"              => "Digite el primer apellido",
    "AYUDA_SEGUNDO_APELLIDO"             => "Digite el segundo apellido",
    "AYUDA_NOMBRE_COMERCIAL"             => "Nombre comercial utilizado por el tercero",
    "AYUDA_DOCUMENTO_MUNICIPIO"          => "Municipio donde pertenece el documento de identidad del tercero",
    "AYUDA_RESIDENCIA_MUNICIPIO"         => "Municipio donde se ubica el tercero",
    "AYUDA_LOCALIDAD"                    => "Seleccione el barrio o corregiemiento donde se ubica el tercero",
    "AYUDA_DIRECCION"                    => "Direccion donde se ubica el tercero",
    "AYUDA_REGIMEN"                      => "Seleccione el regimen tributario",
    "AYUDA_TELEFONO_PRINCIPAL"           => "Telefono principal, digite indicativo si lo requiere",
    "AYUDA_FAX"                          => "Fax, si el tercero no tiene fax puede colocar otro numero de telefono",
    "AYUDA_CELULAR"                      => "Numero de celular del tercero",
    "AYUDA_CORREO"                       => "Correo electronico del tercero, EJEMPLO: micorreo@gmail.com",
    "AYUDA_RESOLUCION_RETEFUENTE"        => "Digite el numero de la resolucion de retencion en la fuente",
    "AYUDA_RESOLUCION_RETEIVA"           => "Digite el numero de la resolucion de retencion de IVA",
    "AYUDA_RESOLUCION_RETEICA"           => "Digite el numero de la resolucion de retencion de ICA",
    "AYUDA_RESOLUCION_CONTRIBUYENTE"     => "Digite el numero de la resolucion de gran contribuyente",
    "AYUDA_SITIO_WEB"                    => "Pagina web del tercero, EJEMPLO: www.mipagina.com",
    "ERROR_EXISTE_DOCUMENTO"             => "Ya existe una tercera persona con ese documento de identidad",
    "ERROR_EXISTE_CODIGO"                => "Ya existe una empresa con ese codigo",
    "ERROR_EXISTE_NOMBRE"                => "Ya existe una empresa con ese nombre ",
    "ERROR_EXISTE_RAZON_SOCIAL"          => "Ya existe una empresa con esa razón social",
    "ERROR_EXISTE_NOMBRE_CORTO"          => "Ya existe una empresa con esa abreviatura",
    "ERROR_EXISTE_FECHA_CIERRE"          => "Ya existe una empresa con esa fecha de cierre",
    "ERROR_EXISTE_ESTADO"                => "Ya existe una empresa con ese estado",
    "ERROR_EXISTE_TERCERO"               => "Ya existe una empresa con ese tercero",
    "ERROR_EXISTE_REGIMEN"               => "Ya existe una empresa con ese regimen",
    "ERROR_FORMATO_CODIGO"               => "El código debe contener solo numeros",
    "ERROR_FORMATO_CODIGO_INTERNO"       => "El código interno debe contener solo numeros",
    "ERROR_FORMATO_COMUNAS"              => "El numero de comunas es incorrrecto",
    "ERROR_EXISTE_GRAN_CONTRIBUYENTE"    => "Ya existe una empresa con ese indicador de gran contribuyente",
    "ERROR_EXISTE_RETENCION_FUENTE"      => "Ya existe una empresa con ese indicador de retencion fuente",
    "ERROR_EXISTE_RETENCION_ICA"         => "Ya existe una empresa con ese indicador de retencion ICA",
    "ERROR_EXISTE_ACTIVIDAD_PRINCIPAL"   => "Ya existe una empresa con ese tipo de actividad economica principal",
    "ERROR_EXISTE_ACTIVIDAD_SECUNDARIA"  => "Ya existe una empresa con ese tipo de actividad economica secundaria",
    // Verificar datos vacios
    "DOCUMENTO_IDENTIDAD_VACIO"          => "Digite el documento de identidad",
    "TIPO_PERSONA_VACIO"                 => "Seleccione el tipo de persona",
    "MUNICIPO_DOCUMENTO_VACIO"           => "Ingrese el mucipio de expedición para el documento de identidad",
    "LOCALIDAD_VACIO"                    => "Ingrese el barrio ó corregimiento",
    "DIRECCION_VACIO"                    => "Ingrese la dirección de la empresa",
    "DIRECCION_DIRECCIONES_VACIO"        => "Ingrese la dirección en la pestaña de direcciones",
    "TIPO_DOCUMENTO_VACIO"               => "Seleccione el tipo documento de identidad",
    "NOMBRE_RAZON_VACIO"                 => "Debe ingresar el nombre o la razon social",
    "APELLIDO_VACIO"                     => "Debe ingresar minimo el primer apelido",
    "NOMBRE_VACIO"                       => "Debe ingresar minimo el primer nombre",
    "CODIGO_VACIO"                       => "Debe ingresar el código interno para la empresa",
    "ESTADO_VACIO"                       => "Debe seleccionar el estado para la empresa",
    "RAZON_EMPRESA_VACIO"                => "Debe ingresar la razon social de la empresa",
    "ACTIVIDAD_VACIO"                    => "Debe seleccionar la actividad economica principal de la empresa.\n Verifique que existen actividades economicas para la localidad donde se ubica la empresa",
    "CREAR_TIPOS_DOCUMENTOS"             => "No existen tipos de documentos de identidad, debe crear por lo menos uno",
    "CREAR_ACTIVIDADES_ECONOMICAS"       => "No existen actividades economicas, debe crear por lo menos una",
    "ESTADO_0"                           => "Inactivo",
    "ESTADO_1"                           => "Activo",
);
?>
