INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AF', 'Afganistán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AL', 'Albania');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('DE', 'Alemania');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AD', 'Andorra');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AO', 'Angola');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AI', 'Anguilla');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AQ', 'Antartida');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AG', 'Antigua y Barbuda');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AN', 'Antillas Holandesas');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SA', 'Arabia Saudí');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('DZ', 'Argelia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AR', 'Argentina');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AM', 'Armenia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AW', 'Aruba');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AU', 'Australia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AT', 'Austria');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AZ', 'Azerbaiyán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BS', 'Bahamas');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BH', 'Bahrein');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BD', 'Bangladesh');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BB', 'Barbados');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BY', 'Bielorrusia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BE', 'Bélgica');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BZ', 'Belice');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BJ', 'Benin');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BM', 'Bermuda');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BT', 'Bhutan');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BO', 'Bolivia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BA', 'Bosnia y Herzegovina');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BW', 'Botswana');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BR', 'Brasil');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BN', 'Brunei');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BG', 'Bulgaria');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BF', 'Burkina Faso');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BI', 'Burundi');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CV', 'Cabo Verde');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KH', 'Camboya');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CM', 'Camerún');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CA', 'Canadá');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TD', 'Chad');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CZ', 'Chequia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CL', 'Chile');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CN', 'China continental');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CY', 'Chipre');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('VA', 'Ciudad del Vaticano');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CO', 'Colombia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KM', 'Comoros');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CG', 'Congo');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CD', 'República Democrática del Congo');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KR', 'Corea del Sur');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KP', 'Corea del Norte');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CI', 'Costa de Marfil');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CR', 'Costa Rica');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('HR', 'Croacia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CU', 'Cuba');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('DK', 'Dinamarca');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('DJ', 'Djibouti');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('DM', 'Dominica');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('EC', 'Ecuador');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('EG', 'Egipto');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SV', 'El Salvador');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AE', 'Emiratos Árabes Unidos');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('ER', 'Eritrea');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SK', 'Eslovaquia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SI', 'Eslovenia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('ES', 'España');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('US', 'Estados Unidos');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('EE', 'Estonia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SJ', 'Islas Svalbard y Jan Mayen');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('ET', 'Etiopía');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('FJ', 'Fiji');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PH', 'Filipinas');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('FI', 'Finlandia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('FR', 'Francia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GA', 'Gabón');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GM', 'Gambia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GS', 'Georgia del Sur e Islas Sandwich del Sur');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GE', 'Georgia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GH', 'Ghana');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GI', 'Gibraltar');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GD', 'Granada');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GR', 'Grecia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GL', 'Groenlandia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GP', 'Guadalupe');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GU', 'Guam');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GT', 'Guatemala');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GY', 'Guyana');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GN', 'Guinea');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GQ', 'Guinea Ecuatorial');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GF', 'Guyana Francesa');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('HT', 'Haití');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NL', 'Holanda');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('HN', 'Honduras');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('HK', 'Hong Kong');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('HU', 'Hungría');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('IN', 'India');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('ID', 'Indonesia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('IQ', 'Irak');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('IR', 'Irán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('IE', 'Irlanda');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('BV', 'Isla Bouvet');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CX', 'Isla Christmas');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('IS', 'Islandia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KY', 'Islas Caimán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CC', 'Islas Cocos');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CK', 'Islas Cook');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MP', 'Islas Marianas');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('FO', 'Islas Faroe');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('HM', 'Islas Heard y McDonald');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AX', 'Islas Åland');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('FK', 'Islas Malvinas');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MH', 'Islas Marshall');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NF', 'Islas Norfolk');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SB', 'Islas Salomón');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TC', 'Islas Turcas y Caicos');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('UM', 'Islas Ultramarinas de Estados Unidos');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('VG', 'Islas Vírgenes Británicas');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('IL', 'Israel');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('IT', 'Italia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('JM', 'Jamaica');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('JP', 'Japón');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('JO', 'Jordania');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KZ', 'Kazajstán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KE', 'Kenia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KG', 'Kirguistán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KI', 'Kiribati');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KW', 'Kuwait');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LA', 'Laos');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LS', 'Lesoto');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LV', 'Letonia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LB', 'Líbano');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LR', 'Liberia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LY', 'Libia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LI', 'Liechtenstein');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LT', 'Lituania');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LU', 'Luxemburgo');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MO', 'Macao');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MK', 'Macedonia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MG', 'Madagascar');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MY', 'Malasia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MW', 'Malawi');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MV', 'Maldivas');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('ML', 'Mali');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MT', 'Malta');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MA', 'Marruecos');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MQ', 'Martinica');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MU', 'Mauricio');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MR', 'Mauritania');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('YT', 'Mayotte');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MX', 'México');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MM', 'Myanmar');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('FM', 'Micronesia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MD', 'Moldavia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MC', 'Mónaco');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MN', 'Mongolia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MS', 'Montserrat');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('MZ', 'Mozambique');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NA', 'Namibia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NR', 'Nauru');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NP', 'Nepal');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NI', 'Nicaragua');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NE', 'Níger');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NG', 'Nigeria');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NU', 'Niue');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NO', 'Noruega');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NC', 'Nueva Caledonia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('NZ', 'Nueva Zelanda');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('OM', 'Omán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PK', 'Pakistán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PW', 'Palau');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PS', 'Palestina');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PA', 'Panamá');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PG', 'Papúa Nueva Guinea');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PY', 'Paraguay');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PE', 'Perú');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PN', 'Pitcairn');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PF', 'Polinesia Francesa');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PL', 'Polonia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PT', 'Portugal');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PR', 'Puerto Rico');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('QA', 'Qatar');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('GB', 'Reino Unido');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CF', 'República Centroafricana');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('DO', 'República Dominicana');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('RE', 'Reunión');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('RW', 'Ruanda');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('RO', 'Rumanía');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('RU', 'Rusia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('EH', 'Sáhara Occidental');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('WS', 'Samoa');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('AS', 'Samoa Americana');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SM', 'San Marino');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('PM', 'St. Pierre y Miquelon');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SH', 'Santa Helena');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('KN', 'Saint Kitts y Nevis');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LC', 'Santa Lucía');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('ST', 'Santo Tomé y Príncipe');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('VC', 'San Vicente y las Granadinas');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SN', 'Senegal');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CS', 'Serbia y Montenegro');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SC', 'Seychelles');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SL', 'Sierra Leona');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SG', 'Singapur');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SY', 'Siria');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SO', 'Somalia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('LK', 'Sri Lanka');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SZ', 'Suazilandia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('ZA', 'Sudáfrica');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SD', 'Sudán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SE', 'Suecia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('CH', 'Suiza');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('SR', 'Surinam');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TH', 'Tailandia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TW', 'Taiwán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TJ', 'Tayikistán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TZ', 'Tanzania');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('IO', 'Territorio Británico del Océano Índico');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TF', 'Territorios Franceses del Sur');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TL', 'Timor Oriental');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TG', 'Togo');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TK', 'Tokelau');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TO', 'Tonga');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TT', 'Trinidad y Tobago');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TM', 'Turkmenistán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TN', 'Túnez');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TR', 'Turquía');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('TV', 'Tuvalu');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('UA', 'Ucrania');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('UG', 'Uganda');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('UY', 'Uruguay');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('UZ', 'Uzbekistán');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('VU', 'Vanuatu');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('VE', 'Venezuela');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('VN', 'Vietnam');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('WF', 'Wallis y Futuna');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('YE', 'Yemen');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('ZM', 'Zambia');
INSERT INTO job_paises (codigo_iso, nombre) VALUES ('ZW', 'Zimbabue');
