INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AF', 1,  'Afganistán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AL', 2,  'Albania');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('DE', 3,  'Alemania');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AD', 4,  'Andorra');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AO', 5,  'Angola');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AI', 6,  'Anguilla');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AQ', 7,  'Antartida');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AG', 8,  'Antigua y Barbuda');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AN', 9,  'Antillas Holandesas');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SA', 10,  'Arabia Saudí');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('DZ', 11, 'Argelia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AR', 12, 'Argentina');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AM', 13, 'Armenia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AW', 14, 'Aruba');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AU', 15, 'Australia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AT', 16, 'Austria');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AZ', 17, 'Azerbaiyán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BS', 18, 'Bahamas');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BH', 19, 'Bahrein');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BD', 20, 'Bangladesh');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BB', 21, 'Barbados');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BY', 22, 'Bielorrusia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BE', 23, 'Bélgica');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BZ', 24, 'Belice');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BJ', 25, 'Benin');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BM', 26, 'Bermuda');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BT', 27, 'Bhutan');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BO', 28, 'Bolivia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BA', 29, 'Bosnia y Herzegovina');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BW', 30, 'Botswana');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BR', 31, 'Brasil');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BN', 32, 'Brunei');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BG', 33, 'Bulgaria');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BF', 34, 'Burkina Faso');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BI', 35, 'Burundi');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CV', 36, 'Cabo Verde');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KH', 37, 'Camboya');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CM', 38, 'Camerún');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CA', 39, 'Canadá');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TD', 40, 'Chad');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CZ', 41, 'Chequia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CL', 42, 'Chile');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CN', 43, 'China continental');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CY', 44, 'Chipre');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('VA', 45, 'Ciudad del Vaticano');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CO', 46, 'Colombia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KM', 47, 'Comoros');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CG', 48, 'Congo');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CD', 49, 'República Democrática del Congo');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KR', 50, 'Corea del Sur');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KP', 51, 'Corea del Norte');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CI', 52, 'Costa de Marfil');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CR', 53, 'Costa Rica');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('HR', 54, 'Croacia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CU', 55, 'Cuba');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('DK', 56, 'Dinamarca');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('DJ', 57, 'Djibouti');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('DM', 58, 'Dominica');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('EC', 59, 'Ecuador');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('EG', 60, 'Egipto');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SV', 61, 'El Salvador');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AE', 62, 'Emiratos Árabes Unidos');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('ER', 63, 'Eritrea');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SK', 64, 'Eslovaquia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SI', 65, 'Eslovenia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('ES', 66, 'España');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('US', 67, 'Estados Unidos');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('EE', 68, 'Estonia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SJ', 69, 'Islas Svalbard y Jan Mayen');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('ET', 70, 'Etiopía');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('FJ', 71, 'Fiji');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PH', 72, 'Filipinas');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('FI', 73, 'Finlandia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('FR', 74, 'Francia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GA', 75, 'Gabón');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GM', 76, 'Gambia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GS', 77, 'Georgia del Sur e Islas Sandwich del Sur');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GE', 78, 'Georgia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GH', 79, 'Ghana');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GI', 80, 'Gibraltar');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GD', 81, 'Granada');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GR', 82, 'Grecia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GL', 83, 'Groenlandia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GP', 84, 'Guadalupe');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GU', 85, 'Guam');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GT', 86, 'Guatemala');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GY', 86, 'Guyana');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GN', 88, 'Guinea');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GW', 89, 'Guinea-Bissau');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GQ', 90, 'Guinea Ecuatorial');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GF', 91, 'Guyana Francesa');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('HT', 92, 'Haití');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NL', 93, 'Holanda');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('HN', 94, 'Honduras');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('HK', 95, 'Hong Kong');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('HU', 96, 'Hungría');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('IN', 97, 'India');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('ID', 98, 'Indonesia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('IQ', 99, 'Irak');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('IR', 100, 'Irán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('IE', 101, 'Irlanda');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('BV', 102, 'Isla Bouvet');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CX', 103, 'Isla Christmas');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('IS', 104, 'Islandia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KY', 105, 'Islas Caimán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CC', 106, 'Islas Cocos');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CK', 107, 'Islas Cook');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MP', 108, 'Islas Marianas');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('FO', 109, 'Islas Faroe');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('HM', 110, 'Islas Heard y McDonald');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AX', 111, 'Islas Åland');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('FK', 112, 'Islas Malvinas');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MH', 113, 'Islas Marshall');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NF', 114, 'Islas Norfolk');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SB', 115, 'Islas Salomón');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TC', 116, 'Islas Turcas y Caicos');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('UM', 117, 'Islas Ultramarinas de Estados Unidos');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('VG', 118, 'Islas Vírgenes Británicas');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('VI', 119, 'Islas Vírgenes de los Estados Unidos');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('IL', 120, 'Israel');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('IT', 121, 'Italia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('JM', 122, 'Jamaica');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('JP', 123, 'Japón');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('JO', 124, 'Jordania');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KZ', 125, 'Kazajstán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KE', 126, 'Kenia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KG', 127, 'Kirguistán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KI', 128, 'Kiribati');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KW', 129, 'Kuwait');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LA', 130, 'Laos');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LS', 131, 'Lesoto');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LV', 132, 'Letonia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LB', 133, 'Líbano');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LR', 134, 'Liberia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LY', 135, 'Libia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LI', 136, 'Liechtenstein');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LT', 137, 'Lituania');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LU', 138, 'Luxemburgo');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MO', 139, 'Macao');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MK', 140, 'Macedonia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MG', 141, 'Madagascar');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MY', 142, 'Malasia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MW', 143, 'Malawi');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MV', 144, 'Maldivas');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('ML', 145, 'Mali');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MT', 146, 'Malta');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MA', 147, 'Marruecos');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MQ', 148, 'Martinica');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MU', 149, 'Mauricio');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MR', 150, 'Mauritania');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('YT', 151, 'Mayotte');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MX', 152, 'México');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MM', 153, 'Myanmar');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('FM', 154, 'Micronesia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MD', 155, 'Moldavia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MC', 156, 'Mónaco');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MN', 157, 'Mongolia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MS', 158, 'Montserrat');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('MZ', 159, 'Mozambique');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NA', 160, 'Namibia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NR', 161, 'Nauru');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NP', 162, 'Nepal');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NI', 163, 'Nicaragua');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NE', 164, 'Níger');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NG', 165, 'Nigeria');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NU', 166, 'Niue');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NO', 167, 'Noruega');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NC', 168, 'Nueva Caledonia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('NZ', 169, 'Nueva Zelanda');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('OM', 170, 'Omán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PK', 171, 'Pakistán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PW', 172, 'Palau');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PS', 173, 'Palestina');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PA', 174, 'Panamá');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PG', 175, 'Papúa Nueva Guinea');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PY', 176, 'Paraguay');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PE', 177, 'Perú');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PN', 178, 'Pitcairn');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PF', 179, 'Polinesia Francesa');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PL', 180, 'Polonia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PT', 181, 'Portugal');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PR', 182, 'Puerto Rico');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('QA', 183, 'Qatar');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('GB', 184, 'Reino Unido');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CF', 185, 'República Centroafricana');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('DO', 186, 'República Dominicana');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('RE', 187, 'Reunión');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('RW', 188, 'Ruanda');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('RO', 189, 'Rumanía');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('RU', 190, 'Rusia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('EH', 191, 'Sáhara Occidental');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('WS', 192, 'Samoa');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('AS', 193, 'Samoa Americana');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SM', 194, 'San Marino');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('PM', 195, 'St. Pierre y Miquelon');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SH', 196, 'Santa Helena');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('KN', 197, 'Saint Kitts y Nevis');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LC', 198, 'Santa Lucía');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('ST', 199, 'Santo Tomé y Príncipe');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('VC', 200, 'San Vicente y las Granadinas');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SN', 201, 'Senegal');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CS', 202, 'Serbia y Montenegro');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SC', 203, 'Seychelles');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SL', 204, 'Sierra Leona');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SG', 205, 'Singapur');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SY', 206, 'Siria');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SO', 207, 'Somalia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('LK', 208, 'Sri Lanka');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SZ', 209, 'Suazilandia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('ZA', 210, 'Sudáfrica');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SD', 211, 'Sudán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SE', 212, 'Suecia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('CH', 213, 'Suiza');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('SR', 214, 'Surinam');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TH', 215, 'Tailandia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TW', 216, 'Taiwán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TJ', 217, 'Tayikistán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TZ', 218, 'Tanzania');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('IO', 219, 'Territorio Británico del Océano Índico');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TF', 220, 'Territorios Franceses del Sur');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TL', 221, 'Timor Oriental');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TG', 222, 'Togo');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TK', 223, 'Tokelau');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TO', 224, 'Tonga');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TT', 225, 'Trinidad y Tobago');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TM', 226, 'Turkmenistán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TN', 227, 'Túnez');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TR', 228, 'Turquía');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('TV', 229, 'Tuvalu');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('UA', 230, 'Ucrania');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('UG', 231, 'Uganda');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('UY', 232, 'Uruguay');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('UZ', 233, 'Uzbekistán');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('VU', 234, 'Vanuatu');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('VE', 235, 'Venezuela');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('VN', 236, 'Vietnam');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('WF', 237, 'Wallis y Futuna');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('YE', 238, 'Yemen');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('ZM', 239, 'Zambia');
INSERT INTO job_paises (codigo_iso, codigo_interno, nombre) VALUES ('ZW', 240, 'Zimbabue');
