<?php
/**
*
* Copyright (C) 2020 Jobdaily
* Raul Mauricio Oidor Lozano <ozzymauricio75@gmail.com>
*
* Este archivo es parte de:
* Jobdaily:: Sofware empresarial a la medida
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los terminos de la Licencia Publica General GNU
* publicada por la Fundacion para el Software Libre, ya sea la version 3
* de la Licencia, o (a su eleccion) cualquier version posterior.
*
* Este programa se distribuye con la esperanza de que sea util, pero
* SIN GARANTIA ALGUNA; ni siquiera la garantia implicita MERCANTIL o
* de APTITUD PARA UN PROPOSITO DETERMINADO. Consulte los detalles de
* la Licencia Publica General GNU para obtener una informacion mas
* detallada.
*
* Deberia haber recibido una copia de la Licencia Publica General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(

    "GESTASPI"                                  => "Aspirantes",
    "ADICASPI"                                  => "Adicionar aspirantes",
    "CONSASPI"                                  => "Consultar aspirantes",
    "MODIASPI"                                  => "Modificar aspirantes",
    "ELIMASPI"                                  => "Eliminar aspirantes",
    "LISTASPI"                                  => "Listar aspirantes",
    "REPORTE_ASPIRANTES"                        => "Reporte de aspirantes",

    "PESTANA_IDENTIFICACION"                    => "Identificación",
    "TIPO_DOCUMENTO"                            => "Tipo de documento",
    "NUMERO_DOCUMENTO"                          => "Número de documento",
    "PRIMER_NOMBRE"                             => "Primer nombre",
    "SEGUNDO_NOMBRE"                            => "Segundo nombre",
    "PRIMER_APELLIDO"                           => "Primer apellido",
    "SEGUNDO_APELLIDO"                          => "Segundo apellido",
    "MUNICIPIO_EXPEDICION_DOCUMENTO"            => "Municipio de expedición",
    "AYUDA_NUMERO_DOCUMENTO"                    => "Número del documento de identificación",
    "AYUDA_PRIMER_NOMBRE"                       => "Primer nombre",
    "AYUDA_SEGUNDO_NOMBRE"                      => "Segundo nombre (opcional)",
    "AYUDA_PRIMER_APELLIDO"                     => "Primer apellido",
    "AYUDA_SEGUNDO_APELLIDO"                    => "Segundo apellido (opcional)",
    "AYUDA_FECHA_NACIMIENTO"                    => "Fecha de nacimiento",
    "AYUDA_MUNICIPIO_EXPEDICION_DOCUMENTO"      => "Municipio donde fue expedido el documento de la persona",
    "ESTADO_CIVIL"                              => "Estado civil",
    "AYUDA_ESTADO_CIVIL"                        => "Estado civil de la persona",
    "SOLTERO"                                   => "Soltero(a)",
    "CASADO"                                    => "Casado(a)",
    "UNION_LIBRE"                               => "Unión libre",
    "DIVORCIADO"                                => "Divorciado(a)",
    "VIUDO"                                     => "Viudo(a)",
    "TIPO_CONTRATACION"                         => "Tipo de contratación",
    "AYUDA_TIPO_CONTRATACION"                   => "Tipo de contratacion del empleado con la empresa",
    "ASPIRANTE_LABORAR"                         => "Aspirante a laborar",
    "LABORA_DIRECTAMENTE"                       => "Termino indefinido",
    "LABORA_POR_CONTRATO"                       => "Contrato Fijo",
    "PRESTACION_SERVICIOS"                      => "Prestación de servicios",
    "FECHA_NACIMIENTO"                          => "Fecha de nacimiento",
    "MUNICIPIO_NACIMIENTO"                      => "Municipio de nacimiento",
    "AYUDA_MUNICIPIO_NACIMIENTO"                => "Municipio de nacimiento de la persona",
    "NUMERO_LIBRETA_MILITAR"                    => "Libreta militar número",
    "AYUDA_NUMERO_LIBRETA_MILITAR"              => "Número correspondiente a la libreta militar",
    "TIPO_LIBRETA"                              => "Clase de libreta militar",
    "AYUDA_TIPO_LIBRETA"                        => "Es la clase a la que corresponde la libreta militar",
    "DISTRITO_MILITAR"                          => "Distrito militar",
    "AYUDA_DISTRITO_MILITAR"                    => "Número del distrito militar donde fue expedida la libreta",
    "NO_TIENE"                                  => "No tiene",
    "PRIMERA_CLASE"                             => "Primera clase",
    "SEGUNDA_CLASE"                             => "Segunda clase",
    "PERMISO_CONDUCCION"                        => "Permiso de conducir",
    "AYUDA_PERMISO_CONDUCCION"                  => "Número del permiso de conducción",
    "CATEGORIA_PERMISO_CONDUCCION"              => "Categoría",
    "AYUDA_CATEGORIA_PERMISO_CONDUCCION"        => "Categoría del pase de conducción",
    "PRIMERA_CATEGORIA"                         => "Primera",
    "SEGUNDA_CATEGORIA"                         => "Segunda",
    "TERCERA_CATEGORIA"                         => "Tercera",
    "CUARTA_CATEGORIA"                          => "Cuarta",
    "QUINTA_CATEGORIA"                          => "Quinta",
    "SEXTA_CATEGORIA"                           => "Sexta",

    "PESTANA_PROFESIONAL"                       => "Profesional",
    "PENSIONADO"                                => "Pensionado",
    "SI_PENSIONADO"                             => "Si",
    "NO_PENSIONADO"                             => "No",
    "PROFESION_OFICIO"                          => "Profesión u oficio",
    "AYUDA_PROFESION_OFICIO"                    => "Profesión u oficio que desempeñara la persona",
    "RECOMENDACION_INTERNA"                     => "Recomendación interna",
    "AYUDA_RECOMENDACION_INTERNA"               => "Persona que lo recomienda y trabaja en la empresa",
    "EXPERIENCIA_LABORAL"                       => "Experiencia laboral",
    "AYUDA_EXPERIENCIA_LABORAL"                 => "Tiempo de experiencia laboral del aspirante",
    "CARGO"                                     => "Cargo",
    "FECHA_INGRESO"                             => "Fecha de postulacion",
    "FECHA_MUDANZA"                             => "Fecha de mudanza",
    "SALARIO_BASE"                              => "Salario base",
    "INGRESO_PENSION"                           => "Ingreso de pensión",
    "AYUDA_INGRESO_PENSION"                     => "Valor del ingreso por pensión",

    "PESTANA_LABORAL"                           => "Laboral",
    "NOMBRE_EMPRESA"                            => "Nombre de la empresa",
    "AYUDA_NOMBRE_EMPRESA"                      => "Nombre de la empresa donde laboro",
    "AYUDA_ACTIVIDAD_ECONOMICA_EMPRESA"         => "Actividad económica principal de la empresa",
    "DIRECCION_EMPRESA"                         => "Dirección de la empresa",
    "AYUDA_DIRECCION_EMPRESA"                   => "Es la dirección de la empresa donde laboró la persona",
    "TELEFONO_EMPRESA"                          => "Teléfono de la empresa",
    "AYUDA_TELEFONO_EMPRESA"                    => "Número telefónico de la empresa",
    "DEPARTAMENTO_EMPRESA"                      => "Departamento de la empresa",
    "MOTIVO_RETIRO"                             => "Motivo de retiro",
    "AYUDA_MOTIVO_RETIRO"                       => "Motivo por el cual se retiró de la empresa",
    "JEFE_INMEDAITO"                            => "Jefe inmediato",
    "AYUDA_JEFE_INMEDAITO"                      => "Jefe inmediato de la empresa",
    "AYUDA_DEPARTAMENTO_EMPRESA"                => "Departamento de la empresa donde laboró",
    "CARGO_EMPRESA"                             => "Cargo que desempeñó",
    "CARGO_EMPRESA_CONYUGUE"                    => "Cargo que desempeña",
    "FECHA_INICIAL_EMPRESA"                     => "Fecha inicial",
    "AYUDA_FECHA_INICIAL_EMPRESA"               => "Fecha en la que comenzó a laborar en la empresa",
    "FECHA_FINAL_EMPRESA"                       => "Fecha final",
    "AYUDA_FECHA_FINAL_EMPRESA"                 => "Fecha en la que finalizó laborares en la empresa",
    "ASPIRACION_SALARIAL"                       => "Aspiración salarial",
    "AYUDA_ASPIRACION_SALARIAL"                 => "Aspiración salarial de la persona",
    "HORARIO_EMPRESA"                           => "Horario laboral",
    "AYUDA_HORARIO_EMPRESA"                     => "Horario laboral que tenía en la empresa",
    "DIRECTO"                                   => "Directo",
    "AGENCIA"                                   => "Agencia",
    "FORMA_CONTRATO"                            => "Contrato",
    "AYUDA_FORMA_CONTRATO"                      => "Forma de contrato que tenía con la empresa la persona",
    "EPS_EMPRESA"                               => "Entidad promotora de salud",
    "PENSION_EMPRESA"                           => "Fondo de pensiones",
    "CESANTIAS_EMPRESA"                         => "Fondo de cesantías",
    "AYUDA_EPS_EMPRESA"                         => "Entidad promotora de salud a la que se encontraba afiliado",
    "AYUDA_PENSION_EMPRESA"                     => "Fondo de pesiones al que se encontraba afiliado",
    "AYUDA_CESANTIAS_EMPRESA"                   => "Fondo de cesantías al que se encontraba afiliado",
    "LOGROS_OBTENIDOS"                          => "Logros obtenidos",
    "AYUDA_LOGROS_OBTENIDOS"                    => "Son los logros que obtuvo en la empresa",

    "PESTANA_PERSONAL"                          => "Personal",
    "ESTATURA"                                  => "Estatura",
    "AYUDA_ESTATURA"                            => "Estatura en centimetros de la persona",
    "PESO"                                      => "Peso",
    "AYUDA_PESO"                                => "Peso en kilogramos de la persona",
    "TALLA_CAMISA"                              => "Camisa",
    "TALLA_PANTALON"                            => "Pantalón",
    "TALLA_CALZADO"                             => "Calzado",
    "AYUDA_TALLA_CAMISA"                        => "Talla de la camisa",
    "AYUDA_TALLA_PANTALON"                      => "Talla del pantalón",
    "AYUDA_TALLA_CALZADO"                       => "Talla del calzado",
    "ANTEOJOS"                                  => "Utiliza anteojos",
    "ANTEOJOS_SI"                               => "Si",
    "ANTEOJOS_NO"                               => "No",
    "SI_ANTEOJOS"                               => "Utiliza anteojos",
    "NO_ANTEOJOS"                               => "No utiliza anteojos",
    "AFICION"                                   => "Afición",
    "LISTA_AFICIONES"                           => "Listado de aficiones",
    "DEPORTE"                                   => "Deporte",
    "LISTA_DEPORTES"                            => "Listado de deportes",

    "PESTANA_UBICACION"                         => "Ubicación",
    "BARRIO_RESIDENCIA"                         => "Barrio o corregimiento de residencia",
    "AYUDA_BARRIO_RESIDENCIA"                   => "Barrio o corregimiento donde la persona reside actualmente",
    "MUNICIPIO_MAYOR_ESTADIA"                   => "Municipio de mayor estadía",
    "AYUDA_MUNICIPIO_MAYOR_ESTADIA"             => "Municipio donde la persona a vivido la mayor parte de su vida",
    "CORREO_ELECTRONICO"                        => "Correo electrónico",
    "CORREO_ELECTRONICO2"                       => "Correo electrónico 2",
    "AYUDA_CORREO_ELECTRONICO"                  => "Es el correo electrónico de la persona",
    "DIRECCION"                                 => "Dirección",
    "TELEFONO"                                  => "Telefono",
    "CELULAR"                                   => "Celular",
    "CELULAR2"                                  => "Celular 2",
    "FAX"                                       => "Fax",
    "SITIO_WEB"                                 => "Sitio web",
    "DERECHO_VIVIENDA"                          => "Derecho sobre vivienda",
    "AYUDA_DERECHO_VIVIENDA"                    => "Derecho sobre vivienda",
    "ARRENDADA"                                 => "Arrendamiento",
    "PROPIA"                                    => "Propiedad",
    "FAMILIAR"                                  => "Familiar",
    "COMODATO"                                  => "Comodato",
    "FECHA_INICIO_VIVIENDA"                     => "Fecha inicial",
    "AYUDA_FECHA_INICIO_VIVIENDA"               => "Fecha en que comenzó a habitar la vivienda",
    "NOMBRE_ARRENDADOR"                         => "Nombre del arrendador",
    "AYUDA_NOMBRE_ARRENDADOR"                   => "Nombre del arrendador de la viviende",
    "MUNICIPIO_ARRENDADOR"                      => "Municipio del arrendador",
    "AYUDA_MUNICIPIO_ARRENDADOR"                => "Municipio de residencia del arrendador",
    "TELEFONO_ARRENDADOR"                       => "Teléfono del arrendatario",
    "AYUDA_TELEFONO_ARRENDADOR"                 => "Telefóno de la persona que arrienda la vivienda",
    "CANON_ARRENDAMIENTO"                       => "Canón de arrendamiento",
    "AYUDA_CANON_ARRENDAMIENTO"                 => "Valor del canon de arrendamiento",
    "AYUDA_MUNICIPIO"                           => "Municipio de residencia",
    "AYUDA_AFICION"                             => "Alguna aficion que tiene la persona",
    "AYUDA_DEPORTE"                             => "Deporte que mas practica la persona",
    "AYUDA_DIRECCION"                           => "Dirección de residencia",
    "AYUDA_TELEFONO"                            => "Número de telefono fijo de contacto",
    "AYUDA_CELULAR"                             => "Número de telefono celular de contacto",
    "AYUDA_FAX"                                 => "Número de fax de contacto",
    "AYUDA_SITIO_WEB"                           => "Dirección de Sitio web de contacto",
    "AYUDA_CARGO"                               => "Cargo que desempeñara en la empresa",
    "AYUDA_CARGO_EMPRESA"                       => "Cargo que desempeñO en la empresa",
    "AYUDA_FECHA_INGRESO"                       => "Fecha de inicio de labores en la empresa",
    "AYUDA_SALARIO_BASE"                        => "Salario base de liquidación",

    "PESTANA_ACADEMICA"                         => "Académica",
    "NOMBRE_TITULO_EDUCACION"                   => "Titulo",
    "TITULO"                                    => "Titulo",
    "NOMBRE_ESCOLARIDAD"                        => "Escolaridad",
    "PRIMARIA"                                  => "Primaria",
    "BACHILLER_CLASICO"                         => "Bachiller clásico",
    "BACHILLER_TECNICO"                         => "Bachiller técnico",
    "BACHILLER_COMERCIAL"                       => "Bachiller comercial",
    "TECNICO"                                   => "Técnico",
    "TECNOLOGO"                                 => "Tecnólogo",
    "PROFESIONAL"                               => "Profesional",
    "POSTGRADO"                                 => "Postgrado",
    "DIPLOMADO"                                 => "diplomado",
    "SEMINARIO"                                 => "seminario",
    "GRADO_EDUCACION"                           => "Escolaridad",
    "AYUDA_GRADO_EDUCACION"                     => "Grado de escolaridad a la que corresponde el estudio realizado",
    "HORARIO_EDUCACION"                         => "Horario",
    "DIURNO"                                    => "Diurno",
    "NOCTURNO"                                  => "Nocturno",
    "AMBAS"                                     => "Ambos",
    "SABATINO"                                  => "Sabatino",
    "AYUDA_HORARIO_EDUCACION"                   => "Horario en que asistia a clases",
    "INTENSIDAD_HORARIA"                        => "Intensidad horaria",
    "AYUDA_INTENSIDAD_HORARIA"                  => "Horas de clase al día",
    "FECHA_INICIAL_EDUCACION"                   => "Fecha de inicio",
    "FECHA_FINAL_EDUCACION"                     => "Fecha de finalización",
    "AYUDA_FECHA_INICIAL_EDUCACION"             => "Fecha de inicio del estudio",
    "AYUDA_FECHA_FINAL_EDUCACION"               => "Fecha en que culminó el estudio",
    "ID_ESCOLARIDAD"                            => "Escolaridad",
    "FECHA_INICIO"                              => "Fecha inicio",
    "FECHA_FIN"                                 => "Fecha finalizacion",
    "INTENSIDAD_HORARIA"                        => "Intensidad horaria",
    "HORARIO_EDUCACION"                         => "Horario",
    "HORARIO"                                   => "Horario",
    "NOMBRE_INSTITUTO_EDUCACION"                => "Institución",
    "INSTITUCION"                               => "Institución",
    "MUNICIPIO_INSTITUCION_EDUCACION"           => "Municipio",
    "ID_MUNICIPIO"                              => "Municipio",
    "AYUDA_NOMBRE_TITULO_EDUCACION"             => "Es el nombre del titulo que posee la persona",
    "AYUDA_NOMBRE_ESCOLARIDAD"                  => "Es el nivel de estudios que posee la persona",
    "AYUDA_NOMBRE_INSTITUTO_EDUCACION"          => "Nombre de la institución donde se realizarón los estudios",
    "AYUDA_MUNICIPIO_INSTITUCION_EDUCACION"     => "Municipio donde se encuentra ubicada la institución",

    "PESTANA_CONYUGUE"                          => "Conyugue",
    "NOMBRE_CONYUGUE "                          => "Nombre completo",
    "EMPRESA_CONYUGUE"                          => "Empresa",
    "AYUDA_EMPRESA_CONYUGUE"                    => "Empresa donde labora el conyugue",
    "TELEFONO"                                  => "Teléfono",
    "CELULAR_CONYUGUE"                          => "Celular",
    "AYUDA_CELULAR_CONYUGUE"                    => "Número de celular donde se localiza al conyugue",
    "AYUDA_TELEFONO_CONYUGUE"                   => "Teléfono de la oficina del conyugue",

    "PESTANA_FAMILIAR"                          => "Familiar",
    "NOMBRE_FAMILIAR"                           => "Nombre del familiar",
    "NOMBRE_COMPLETO"                           => "Nombre y apellidos",
    "TIPO_DOCUMENTO_FAMILIAR"                   => "Tipo documento",
    "ID_TIPO_DOCUMENTO"                         => "Tipo documento",
    "NUMERO_DOCUMENTO_FAMILIAR"                 => "Numero documento",
    "DOCUMENTO_IDENTIDAD"                       => "Numero documento",
    "DEPENDENCIA_FAMILIAR"                      => "Depende economicamente",
    "DEPENDE_ECONOMICAMENTE"                    => "Depende economicamente",
    "FECHA_NACIMIENTO_FAMILIAR"                 => "Fecha nacimiento",
    "PROFESION_FAMILIAR"                        => "Profesion",
    "ID_PROFESION"                              => "Profesion",
    "GENERO_FAMILIAR"                           => "Genero",
    "AYUDA_NOMBRE_FAMILIAR"                     => "Nombre de un familiar",
    "HIJO"                                      => "Hijo(a)",
    "PADRE"                                     => "Padre",
    "MADRE"                                     => "Madre",
    "HERMANO"                                   => "Hermano(a)",
    "ABUELO"                                    => "Abuelo(a)",
    "OTRO"                                      => "Otro",
    "RELACION_FAMILIAR"                         => "Parentesco",
    "PARENTESCO"                                => "Parentesco",
    "AYUDA_RELACION_FAMILIAR"                   => "Parentesco que posee con la persona",
    "GENERO"                                    => "Genero",
    "GENERO_MASCULINO"                          => "Masculino",
    "GENERO_FEMENINO"                           => "Femenino",
    "NO_APLICA"                                 => "No aplica",
    "DEPENDENCIA_ECONOMICA"                     => "Depende económicamente",
    "DEPENDENCIA_ECONOMICA_SI"                  => "Si",
    "DEPENDENCIA_ECONOMICA_NO"                  => "No",

    "PESTANA_VEHICULO"                          => "Vehículo",
    "TIPO_VEHICULO"                             => "Tipo de vehiculo",
    "AYUDA_TIPO_VEHICULO"                       => "Tipo de vehiculo que posee la persona",
    "MOTOCICLETA"                               => "Motocicleta",
    "VEHICULO_PARTICULAR"                       => "Vehículo particular",
    "VEHICULO_PUBLICO"                          => "Vehículo de servicio público",
    "CAMION_PEQUENO"                            => "Vehículo de carga pequeño",
    "CAMION_GRANDE"                             => "Vehículo de carga grande",
    "BUS_COLECTIVO_BUSETA"                      => "Bus, Buseta, Colectivo",
    "MODELO_VEHICULO"                           => "Modelo del vehículo",
    "MODELO"                                    => "Modelo",
    "MARCA_VEHICULO"                            => "Marca del vehículo",
    "MARCA"                                     => "Marca",
    "AYUDA_MODELO_VEHICULO"                     => "Es el modelo del vehículo de la persona",
    "AYUDA_MARCA_VEHICULO"                      => "Es la marca del vehículo de la persona",
    "PLACA_VEHICULO"                            => "Matricula",
    "MATRICULA"                                 => "Matricula",
    "AYUDA_PLACA_VEHICULO"                      => "Matricula del vehículo",
    "PIGNORADO"                                 => "Pignorado",
    "SI_PIGNORADO"                              => "Si",
    "NO_PIGNORADO"                              => "No",

    "PESTANA_VIVIENDA"                          => "Vivienda",
    "TIPO_VIVIENDA"                             => "Tipo de vivienda",
    "AYUDA_TIPO_VIVIENDA"                       => "Tipo de vivienda que posee la persona",
    "CASA"                                      => "Casa",
    "APARTAMENTO"                               => "Apartamento",
    "MEJORA"                                    => "Mejora",
    "LOTE"                                      => "Lote",
    "EDIFICIO"                                  => "Edificio",
    "TIPO_VIVIENDA"                             => "Tipo",
    "TIPO"                                      => "Tipo",
    "DIRECCION_VIVIENDA"                        => "Dirección",
    "MUNICIPIO_VIVIENDA"                        => "Municipio",
    "ID_MUNICIPIO"                              => "Municipio",
    "BARRIO"                                    => "Barrio o Corregimiento",
    "TELEFONO_VIVIENDA"                         => "Teléfono",
    "HIPOTECA"                                  => "Hipóteca",
    "SI_HIPOTECA"                               => "Si",
    "NO_HIPOTECA"                               => "No",
    "MUNICIPIO_VIVIENDA"                        => "Municipio de vivienda",
    "MUNICIPIO"                                 => "Municipio",
    "AYUDA_MUNICIPIO_VIVIENDA"                  => "Municipio donde se encuentra ubicada la propiedad",
    "TELEFONO_VIVIENDA"                         => "Teléfono",
    "AYUDA_TELEFONO_VIVIENDA"                   => "Número telefónico que tiene la vivienda",
    "BARRIO_VIVIENDA"                           => "Barrio o corregimiento de ubicación",
    "AYUDA_BARRIO_VIVIENDA"                     => "Barrio o corregimiento donde se encuentra ubicada la propiedad",

    "PESTANA_REFERENCIAS"                       => "Referencias",
    "NOMBRE_REFERENCIA"                         => "Nombre",
    "AYUDA_NOMBRE_REFERENCIA"                   => "Nombre de la persona que da la recomendación",
    "DIRECCION_REFERENCIA"                      => "Dirección",
    "AYUDA_DIRECCION_REFERENCIA"                => "Dirección donde reside la persona de referencia",
    "TELEFONO_REFERENCIA"                       => "Teléfono",
    "PROFESION_REFERENCIA"                      => "Profesion",
    "AYUDA_TELEFONO_REFERENCIA"                 => "Teléfono de la persona que hace la referencia",

    "PESTANA_IDIOMAS"                           => "Idiomas",
    "IDIOMAS"                                   => "Idioma",
    "AYUDA_IDIOMAS"                             => "Idioma que domina la persona",
    "LECTURA"                                   => "Lectura",
    "ESCRITURA"                                 => "Escritura",
    "HABLA"                                     => "Habla",
    "LO_HABLA"                                  => "__Lo habla",
    "LO_HABLA_EXCELENTE"                        => "Excelente",
    "LO_HABLA_BIEN"                             => "Bien",
    "LO_HABLA_REGULAR"                          => "Regular",
    "LO_LEE"                                    => "____Lo lee",
    "LO_LEE_EXCELENTE"                          => "Excelente",
    "LO_LEE_BIEN"                               => "Bien",
    "LO_LEE_REGULAR"                            => "Regular",
    "LO_ESCRIBE"                                => "Lo escribe",
    "LO_ESCRIBE_EXCELENTE"                      => "Excelente",
    "LO_ESCRIBE_BIEN"                           => "Bien",
    "LO_ESCRIBE_REGULAR"                        => "Regular",
    "NO_APLICA"                                 => "No aplica",

    "PESTANA_SISTEMAS"                          => "Sistemas",
    "HOJAS_CALCULO"                             => "_____Hojas de calculo",
    "PROCESADOR_TEXTO"                          => "Procesadores de texto",
    "DIAPOSITIVAS"                              => "Diseño de diapositivas",
    "MUY_BIEN"                                  => "Muy bien",
    "BIEN"                                      => "Bien",
    "REGULAR"                                   => "Regular",
    "NO_SABE"                                   => "No sabe",
    "CUALES"                                    => "Cuales",
    "AYUDA_CUALES_PROGRAMAS"                    => "Escriba algunos de los programas que conoce",
    "AYUDA_CUALES_LENGUAJES"                    => "Escriba algunos de los lenguajes en los que ha programado",
    "PROGRAMADOR_SISTEMAS"                      => "Lenguajes de programacion que conoce",
    "AYUDA_PROGRAMADOR_SISTEMAS"                => "Indica sí la persona ha utlizado lenguajes de programación",
    "DIGITADOR_SISTEMAS"                        => "Programas que maneja",
    "AYUDA_DIGITADOR_SISTEMAS"                  => "Indica sí la persona ha utlizado programas contables y/o comerciales",

    "EMPRESA"                                   => "Empresa",
    "TELEFONO_EMPRESA_TABLA"                    => "Teléfono",
    "DEPARTAMENTO_EMPRESA_TABLA"                => "Departamento",
    "ID_DEPARTAMENTO"                           => "Departamento",
    "CARGO_EMPRESA_TABLA"                       => "Cargo",
    "ID_CARGO"                                  => "Cargo",
    "ACTIVIDAD_ECONOMICA_EMPRESA"               => "Actividad economica",
    "DIRECCION_EMPRESA_TABLA"                   => "Direccion",
    "JEFE_INMEDIATO_EMPRESA_TABLA"              => "Jefe inmediato",
    "JEFE_INMEDIATO"                            => "Jefe inmediato",
    "FECHA_INICIAL_EMPRESA_TABLA"               => "Fecha inicial",
    "FECHA_INICIAL"                             => "Fecha inicial",
    "FECHA_FINAL_EMPRESA_TABLA"                 => "Fecha final",
    "FECHA_FINAL"                               => "Fecha final",
    "HORARIO_EMPRESA_TABLA"                     => "Horario",
    "HORARIO_LABORAL"                           => "Horario",
    "FORMA_CONTRATO_EMPRESA_TABLA"              => "Contrato",
    "MOTIVO_RETIRO_EMPRESA_TABLA"               => "Motivo retiro",
    "ID_MOTIVO_RETIRO"                          => "Motivo retiro",
    "SALUD_EMPRESA_TABLA"                       => "Salud",
    "ID_SALUD"                                  => "Salud",
    "PENSION_EMPRESA_TABLA"                     => "Pension",
    "ID_PENSION"                                => "Pension",
    "CESANTIAS_EMPRESA_TABLA"                   => "Cesantias",
    "ID_CESANTIAS"                              => "Cesantias",
    "LOGROS_EMPRESA_TABLA"                      => "Logros Obtenidos",
    "RELACION_LABORAL"                          => "Relacion laboral",
    "DATO_VACIO"                                => "",
    "SI"                                        => "Si",
    "NO"                                        => "No",
    "EXCELENTE"                                 => "Excelente",
    "NOMBRE"                                    => "Nombre",

    "ERROR_EXISTE_DOCUMENTO"                    => "Ya existe un empleado con este numero de documento",
    "ERROR_DOCUMENTO_IDENTIDAD_VACIO"           => "Error, Documento de identidad vacio. Pestaña Identificacion",
    "ERROR_MUNICIPIO_DOCUMENTO_VACIO"           => "Error, Municipio de expedicion vacio. Pestaña Identificacion",
    "ERROR_PRIMERO_NOMBRE_VACIO"                => "Error, Primer nombre vacio. Pestaña Identificacion",
    "ERROR_PRIMER_APELLIDO_VACIO"               => "Error, Primer apellido vacio. Pestaña Identificacion",
    "ERROR_MUNICIPIO_NACIMIENTO_VACIO"          => "Error, Municipio de nacimiento vacio. Pestaña Identificacion",
    "ERROR_MUNICIPIO_RESIDENCIA_VACIO"          => "Error, Barrio o corregimiento de residencia vacio. Pestaña Ubicacion",
    "ERROR_MUNICIPIO_MAYOR_ESTADIA_VACIO"       => "Error, Municipio de mayor estadia vacio. Pestaña Ubicacion",
    "ERROR_PROFESION_OFICIO_VACIO"              => "Error, Profesion u oficio vacio. Pestaña Profesional",
    "ERROR_DOCUMENTO_IDENTIDAD_CONYUGUE_VACIO"  => "Error, Documento de identidad de conyugue vacio. Pestaña Conyugue",
    "ERROR_PRIMERO_NOMBRE_CONYUGUE_VACIO"       => "Error, Primer nombre de conyugue vacio. Pestaña Conyugue",
    "ERROR_PRIMER_APELLIDO_CONYUGUE_VACIO"      => "Error, Primer apellido de conyugue vacio. Pestaña Conyugue",
    "ERROR_LIBRETA_VACIO"                       => "Error, Si tiene libreta militar entonces libreta militar y distrito militar no deben estar vacios. Pestaña Identificacion",
    "ERROR_PERMISO_VACIO"                       => "Error, Si tiene permiso de conducir entonces este no debe quedar vacio. Pestaña Identificacion",
    "ERROR_PENSIONADO_VACIO"                    => "Error, Si tiene pension debe digitar el valor. Pestaña Profesional",

    "ERROR_NO_EXISTE_MUNICIPIO_DOCUMENTO"       => "Error, no existe Municipio de expedicion en la base de datos, verifique.Pestaña Identificacion",
    "ERROR_NO_EXISTE_MUNICIPIO_NACINIENTO"      => "Error, no existe Municipio de nacimiento en la base de datos, verifique.Pestaña Identificacion",
    "ERROR_NO_EXISTE_MUNICIPIO_RESIDENCIA"      => "Error, no existe Barrio o corregimiento de residencia en la base de datos, verifique.Pestaña Ubicacion",
    "ERROR_NO_EXISTE_MUNICIPIO_ARRENDATARIO"    => "Error, no existe Municipio del arendatario en la base de datos, verifique.Pestaña Ubicacion",
    "ERROR_NO_EXISTE_MUNICIPIO_MAYOR_ESTADIA"   => "Error, no existe Municipio de mayor estadia en la base de datos, verifique.Pestaña Ubicacion",
    "ERROR_NO_EXISTE_PROFESION"                 => "Error, no existe Profesion u oficio en la base de datos, verifique.Pestaña Profesional",
    "ERROR_NO_EXISTE_PROFESION_CONYUGUE"        => "Error, no existe Profesion u oficio del conyugue en la base de datos, verifique.Pestaña Conyugue",

    "ERROR_ACTIVIDAD_NO_EXISTE"                 => "Error, la actividad economica digitada no existe en la base de datos",
    "ERROR_DATOS_VACIOS_LABORAL"                => "Error, es necesario el nombre de la empresa y la actividad economica",
    "ERROR_DATOS_VACIOS_ACADEMICA"              => "Error, son necesarios los datos de escolaridad, titulo, institucion y municipio",
    "ERROR_ESCOLARIDAD_NO_EXISTE"               => "Error, la escolaridad digitada no existe en la base de datos",
    "ERROR_MUNICIPIO_NO_EXISTE"                 => "Error, el municipio digitado no existe en la base de datos",
    "ERROR_EXISTE_FAMILIAR"                     => "Error, ya existe un familiar con la misma identificacion",
    "ERROR_DATOS_VACIOS_FAMILIAR"               => "Error, es necesario el campo Nombre del familiar",
    "ERROR_PROFESION_NO_EXISTE"                 => "Error, la profesion u oficio digitada no existe en la base de datos",
    "ERROR_IDIOMA_EXISTE"                       => "Error, el idioma ya esta cargado. Seleccione otro",
    "ERROR_DATOS_VACIOS_VIVIENDA"               => "Error, son necesarios todos los datos para agregar a la tabla la vivienda",
    "ERROR_DATOS_VACIOS_VEHICULO"               => "Error, son necesarios todos los datos para agregar el vehiculo a la tabla",
    "ERROR_DATOS_VACIOS_REFERENCIA"             => "Error, son necesarios los campos nombre y profesion",
    "ERROR_NO_EXISTEN_REFERENCIAS"              => "Error, debe agregar por lo menos una referencia. Pestaña referencias",

    "ERROR_TABLAS_VACIAS"                       => "Error, las siguientes tablas requeren datos para generar un aspirante\n\n",
    "ERROR_TABLA_VACIA_TIPOS_DOCUMENTOS"        => "- Tipos de documento de identidad\n",
    "ERROR_TABLA_VACIA_MUNICIPIOS"              => "- Municipios\n",
    "ERROR_TABLA_VACIA_LOCALIDADES"             => "- Barrios o corregimientos\n",
    "ERROR_TABLA_VACIA_PROFESIONES"             => "- Profesiones u oficios\n",
    "ERROR_TABLA_VACIA_ENTIDADES"               => "- Entidades parafiscales\n",
    "ERROR_TABLA_VACIA_CONTRATOS"               => "- Tipos de contratos\n",
    "ERROR_TABLA_VACIA_ACTIVIDADES"             => "- Actividades economicas\n",
    "ERROR_TABLA_VACIA_MOTIVOS_RETIRO"          => "- Motivos de retiro\n",
    "ERROR_TABLA_VACIA_CARGOS"                  => "- Cargos\n",
    "ERROR_TABLA_VACIA_DEPARTAMENTOS"           => "- Departamentos de empresa\n",
    "ERROR_TABLA_VACIA_ESCOLARIDAD"             => "- Escolaridad\n",
    "ERROR_TABLA_VACIA_IDIOMAS"                 => "- Idiomas\n",
    "ERROR_TABLA_VACIA_AFICIONES"               => "- Aficiones\n",
    "ERROR_TABLA_VACIA_DEPORTES"                => "- Deportes\n",
    "ERROR_PREFERENCIA_DOCUMENTO"                => "- Preferencias globales (Tipo de documento de identidad, aspirante)\n",
    "EDAD"                                      => "Edad",
    "TIPO_SANGRE"                               => "Tipo de sangre",
    "AYUDA_TIPO_SANGRE"                         => "Tipo de sangre del aspirante. Ejemplo: B+",

    "TERCERO_INICIAL"                           => "Documento desde",
    "TERCERO_FINAL"                             => "Documento hasta",
    "FECHA_DESDE"                               => "Fecha nacimiento desde",
    "FECHA_HASTA"                               => "Fecha nacimiento hasta",
    "ERROR_DOCUMENTO_IDENTIDAD_2"               => "Debe digitar el documento de identidad Inicial",
    "TIPO_LISTADO"                              => "Tipo de listado",
    "AYUDA_TIPO_LISTADO"                        => "Seleccione el tipo de listado a generar",
    "TIPO_DOCUMENTO"                            => "Tipo documento",
    "LUGAR_RESIDENCIA"                          => "Lugar de residencia",
    "LOCALIDAD"                                 => "Localidad",
    "AYUDA_LOCALIDAD"                           => "Digite el nombre de la localidad o barrio de residencia",
    "AYUDA_DOCUMENTO_IDENTIDAD"                 => "Seleccione el tipo de documento de identidad"
);
?>
