<?php
/**
*
* Copyright (C) 2020 Jobdaily
* Raul Mauricio Oidor Lozano <ozzymauricio75@gmail.com>
*
* Este archivo es parte de:
* Jobdaily:: Sofware empresarial a la medida
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los terminos de la Licencia Publica General GNU
* publicada por la Fundacion para el Software Libre, ya sea la version 3
* de la Licencia, o (a su eleccion) cualquier version posterior.
*
* Este programa se distribuye con la esperanza de que sea util, pero
* SIN GARANTIA ALGUNA; ni siquiera la garantia implicita MERCANTIL o
* de APTITUD PARA UN PROPOSITO DETERMINADO. Consulte los detalles de
* la Licencia Publica General GNU para obtener una informacion mas
* detallada.
*
* Deberia haber recibido una copia de la Licencia Publica General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(
    "GESTPTEM"                             => "Prestamos empleados",
    "ADICPTEM"                             => "Adicionar Prestamo",
    "MODIPTEM"                             => "Modificar Prestamo",
    "CONSPTEM"                             => "Consultar Prestamo",
    "ELIMPTEM"                             => "Eliminar Prestamo",
    "LISTPTEM"                             => "Listar Prestamos",
    "REPORTE_PRESTAMOS"                    => "Reporte de prestamos a empleados",
    "PESTANA_SUCURSALES"                   => "Almacenes",
    "SELECCIONAR_TODOS"                    => "Seleccionar todos",
    "PESTANA_BASICA"                       => "Básica",
    "EMPLEADO"                             => "Empleado",
    "AYUDA_EMPLEADOS"                      => "Empleado que solicita el prestamo",
    "CONCEPTO_PRESTAMO"                    => "Concepto del prestamo",
    "AYUDA_CONCEPTO_PRESTAMO"              => "Concepto por el cual solicita el prestamo",
    "SUCURSAL_LABORA"                      => "Almacen",
    "AYUDA_SUCURSAL_LABORA"                => "Alamacen que genera el prestamo",
    "TIPO_DOCUMENTO"                       => "Tipo de documento",
    "NUMERO_DOCUMENTO"                     => "Documento identidad",
    "VALOR_PRESTAMO"                       => "Valor del prestamo",
    "AYUDA_VALOR_PRESTAMO"                 => "valor total del prestamo",
    "FORMA_PAGO"                           => "Forma de pago",
    "MENSUAL"                              => "Mensual",
    "VALOR_MENSUAL"                        => "Pago mensual",
    "QUINCENAL"                            => "Quincenal",
    "PRIMERA_QUINCENA"                     => "Primera quincena",
    "SEGUNDA_QUINCENA"                     => "segunda quincena",
    "VALOR_PRIMERA_QUINCENA"               => "Pago primera quincena",
    "VALOR_SEGUNDA_QUINCENA"               => "Pago segunda quincena",
    "VALOR_PROPORCION_QUINCENA"            => "Pago Proporcional quincenal",
    "SEMANAL"                              => "Semanal",
    "PRIMERA_SEMANA"                       => "Primer semana",
    "SEGUNDA_SEMANA"                       => "Segunda semana",
    "TERCERA_SEMANA"                       => "Tercer semana",
    "CUARTA_SEMANA"                        => "Cuarta semana",
    "VALOR_PRIMERA_SEMANA"                 => "Pago primera semana",
    "VALOR_SEGUNDA_SEMANA"                 => "Pago segunda semana",
    "VALOR_TERCERA_SEMANA"                 => "Pago tercera semana",
    "VALOR_CUARTA_SEMANA"                  => "Pago cuarta semana",
    "VALOR_PROPORCION_SEMANAL"             => "Pago proporcional semanal",
    "OBSERVACIONES"                        => "Observaciones",
    "AYUDA_OBSERVACIONES"                  => "Digite las observaciones para el prestamo",
    "TRANSACCION_CONTABLE"                 => "Transaccion contable",
    "AYUDA_TRANSACCION_CONTABLE"           => "Digite la transaccion contable que corresponde al prestamo",
    "AMBAS_QUINCENAS"                      => "Proporcional quincenal",
    "TODAS_SEMANAS"                        => "Proporcional semanal",
    "USUARIO_SIN_PRIVILEGIOS"              => "El usuario no tiene privilegios",
    "AYUDA_VALOR_PRIMERA_QUINCENA"         => "Valor primera quincena",
    "AYUDA_VALOR_SEGUNDA_QUINCENA"         => "Valor Segunda quincena",

    "PRIMERA_SEMANA"                       => "Primera semana",
    "SEGUNDA_SEMANA"                       => "Segunda semana",
    "TERCERA_SEMANA"                       => "Tercera semana",
    "CUARTA_SEMANA"                        => "Cuarta semana",
    "QUINTA_SEMANA"                        => "Quinta semana",
    "PROPOCIONAL"                          => "Proporcional",
    "PRIMERA_QUINCENA"                     => "Primera quincena",
    "SEGUNDA_QUINCENA"                     => "Segunda quincena",
    "MENSUAL"                              => "Mensual",
    "AYUDA_FORMA_PAGO"                     => "Forma en que se va a realizar el pago del prestamo",
    "FORMA_PAGO"                           => "Forma de pago",
    "AYUDA_VALOR_DESCUENTO"                => "Valor que se va a descontar",
    "VALOR_DESCUENTO"                      => "Valor cuota",
    "FECHAS_GENERADAS"                     => "Fechas generadas",
    "FECHA_DESCUENTO"                      => "Fecha de descuento",
    "SALDO_ACTUAL"                         => "Saldo Actual",
    "PERMITE_DESCUENTO"                    => "Permite descuento",
    "GENERAR_FECHAS"                       => "Generar",
    "ERROR_VACIO_EMPLEADO"                 => "Error, No ha seleccionado un empleado",
    "ERROR_VACIO_TRANSACCION"              => "Error, No ha seleccionado una transacción contable",
    "ERROR_VACIO_VALOR_PRESTAMO"           => "Error, No ha ingresado un valor del prestamo",
    "ERROR_VACIO_VALOR_ABONO"              => "Error, No ha ingresado un valor de cuota",
    "VALOR_CUOTA"                          => "Valor de cuota",
    "PERMITE_DESCUENTO"                    => "No descontar",
    "SALDO_ACTUAL"                         => "Valor de la deuda actual",
    "FECHAS_INICIALES"                     => "fechas iniciales",
    "ERROR_VALOR_PRESTAMO"                 => "El valor del pretamo no puede se menor a",
    "ERROR_VALOR_CUOTA"                    => "El valor del la cuota no puede se menor a",
    "AYUDA_TIPO_DOCUMENTO"                 => "Seleccione el tipo de documento para el movimiento",
    "CUENTA_BANCARIA"                      => "Cuenta bancaria",
    "CONSECUTIVO_CHEQUE"                   => "Consecutivo cheque",
    "AYUDA_CONSECUTIVO_CHEQUE"             => "Número del cheque que genera el documento",
    "CUENTA"                               => "Cuenta",
    "AYUDA_CUENTA"                         => "Cuenta del plan contable por donde se retira el dinero que se presta al empleado",
    "DEBITO"                               => "Debito",
    "CREDITO"                              => "Credito",
    "SENTIDO"                              => "Sentido",
    "AYUDA_SENTIDO"                        => "Sentido de la transacción",
    "MENSAJE_PERIODO_CONTABLE"             => "Este almacen tiene actualmente el periodo contable cerrado para esta operación",
    "CONSECUTIVO_DOCUMENTO"                => "Número documento",
    "AYUDA_CONSECUTIVO_DOCUMENTO"          => "Número del documento que genera el saldo",
    "CUENTAS_BANCARIAS_VACIAS"             => "El tipo de documento seleccionado genera cheques y no existen cuentas bancarias\npara este documento en el almacen que genera seleccionada.\nFavor verifique",
    "MENSAJE"                              => "Las siguientas tablas deben contener un registro.\n\n",
    "SUCURSALES"                           => "-Almacenes \n",
    "EMPLEADOS"                            => "-Empleados \n",
    "TIPOS_DOCUMENTOS"                     => "-tipos de documentos \n",
    "PLAN_CONTABLE"                        => "-Cuentas en el plan contable \n",
    "CONCEPTO_PRESTAMOS"                   => "-Conceptos de prestamos \n",
    "CONSECUTIVO_DOCUMENTO_VACIO"          => "Debe ingresar un número de consecutivo.",
    "CONSECUTIVO_DOCUMENTO_EXISTE"         => "Ya existe un documento con el mismo consecutivo.",
    "VALOR_CUOTA_MAYOR"                    => "El valor de la cuota no debe ser mayor al valor del prestamo.",
    "FECHA_PRESTAMO"                       => "Fecha prestamo",
    "AYUDA_PRESTAMO"                       => "Fecha en que inicia el prestamo",
    "MENSAJE_VACIO_CAMPOS"                 => "Los siguientes campos son obligatorios \n \n ",
    "VACIO_VALOR_DESCONTAR"                => " - Valor de cuotas \n ",
    "VACIO_VALOR_PRESTAMO"                 => " - Valor del prestamo \n ",
    "VACIO_NOMBRE_EMPLEADO"                => " - Nombre del empleado\n ",
    "ERROR_GENERAR_FECHAS"                 => "Error : para realizar el registro de prestamos debe generar las fechas de pago.",
    "NO_EXISTE_TABLA"                      => "Error, las siguientes tablas requieren datos para generar un prestamo \n \n - Tablas (Nombre de la tabla : movimientos_prestamos_generados_empleados) \n ",
    "NO_ACTUALIZADO_TABLA"                 => "Usted ha realizado un cambio en un valor de cuota de la tabla, por favor actualice los datos.",
    "NO_ACTUALIZADO_CUOTAS"                => "Usted ha realizado un cambio en el valor de cuotas, por favor oprima el boton generar en la pestaña Fechas generadas para actualizar los datos.",

    "ERROR_ADICIONAR_CONTRO_PRESTAMO"      => "Se ha generado un error al momento de registrar datos en cotrol prestamos empleados, Tabla: control_prestamos_empleados",
    "ERROR_ADICIONAR_MOVIMIENTO_PRESTAMO"  => "Se ha generado un error al momento de registrar datos en movimientos prestamos empleados, Tabla: movimientos_prestamos_empleados",
    "ERROR_ADICIONAR_FECHAS"               => "Se ha generado un error al momento de registrar datos en fechas prestamos empleados, Tabla: fechas_prestamos_empleados",

    "TRANSACCION_CONTABLE_DESCONTAR"       => "Cuenta por descontar empleado",
    "TRANSACCION_CONTABLE_COBRAR"          => "Cuenta por cobrar empleado",

    "AYUDA_TRANSACCION_CONTABLE_DESCONTAR" => "Transaccion contable con la cual se le descontara al empleado por planilla",
    "AYUDA_TRANSACCION_CONTABLE_COBRAR"    => "Transaccion contable con la cual se le cobrara al empleado",
    "ERROR_PREFERENCIA_CUOTA_MINIMA"       => "La preferencia por empresa de cuota minima en prestamos empleados no esta creada para esta empresa",
    "ERROR_TIPO_DOCUMENTO"                 => "Seleccione un tipo de documento",
    "ERROR_CODIGO_CONTABLE"                => "Debe ingresar una cuenta de un codigo contable",
    "DEUDA_PAGADA"                         => "Pagos realizados",
    "DEUDA_PENDIENTE"                      => "Pagos pendientes",
    "DESDE_HASTA"                          => "Fecha desde&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fecha hasta",
    "APELLIDO_NOMBRE"                      => "Apellido-Nombre",
    "NOMBRE_APELLIDO"                      => "Nombre-Apellido",
    "CEDULA"                               => "Documento",
    "PDF"                                  => "Pdf",
    "PLANO"                                => "Plano para excel",
    "ORDEN_EMPLEADO"                       => "Orden empleado",
    "AYUDA_ORDEN_EMPLEADO"                 => "Seleccione el orden en que aparecen los empleados",
    "TIPO_LISTADO"                         => "Tipo listado",
    "AYUDA_TIPO_LISTADO"                   => "Seleccion el tipo de listado a generar",
    "TOTAL_SUCURSAL"                       => "Total almacen",
    "ARCHIVO_GENERADO"                     => "Archivo generado satisfactoriamente",
    "ERROR_SUCURSAL_VACIA"                 => "Seleccione un almacen",
    "ERROR_FECHA_VACIA"                    => "Seleccione las fechas para listar la información",
    "TOTAL_EMPLEADO"                       => "Total empleado",
    "AYUDA_SUCURSAL"                       => "Marque la casilla para seleccionar o quitar la seleccion",
    "ERROR_SUCURSALES"                     => "-Sucursales",
    "ERROR_EMPLEADOS"                      => "-Empleados",
    "ERROR_SUCURSAL_VACIA"                 => "Seleccione un almacen",
    "ERROR_FECHA_VACIA"                    => "Seleccione las fechas para listar la información",
    "AYUDA_FECHA"                          => "Seleccione las fechas para el listado",
    "FECHA"                                => "Fecha",
    "FECHAS"                               => "Fechas",
    "AYUDA_EMPLEADO"                       => "Digite el nombre del empleado",

 );
?>
