<?php

/**
*
* Copyright (C) 2020 Jobdaily
* Raul Mauricio Oidor Lozano <ozzymauricio75@gmail.com>
*
* Este archivo es parte de:
* Jobdaily:: Sofware empresarial a la medida
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los términos de la Licencia Pública General GNU
* publicada por la Fundación para el Software Libre, ya sea la versión 3
* de la Licencia, o (a su elección) cualquier versión posterior.
*
* Este programa se distribuye con la esperanza de que sea útil, pero
* SIN GARANTÍA ALGUNA; ni siquiera la garantía implícita MERCANTIL o
* de APTITUD PARA UN PROPÓSITO DETERMINADO. Consulte los detalles de
* la Licencia Pública General GNU para obtener una información más
* detallada.
*
* Debería haber recibido una copia de la Licencia Pública General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(
    "GESTMOCO"                              => "Movimientos contables",
    "ADICMOCO"                              => "Adicionar movimientos contables",
    "CONSMOCO"                              => "Consultar movimientos contables",
    "MODIMOCO"                              => "Modificar movimientos contables",
    "ANULMOCO"                              => "Anular movimientos contables",
    "REPOMOCO"                              => "Reportes contables",

    "PESTANA_GENERAL"                       => "General",
    "PESTANA_MOVIMIENTOS"                   => "Movimientos",
    "PESTANA_BALANCE_COMPROBACION"          => "Balance de comprobación",
    "PESTANA_BALANCE_GENERAL"               => "Balance general",
    "PESTANA_PYG"                           => "Perdidas y ganancias",
    "DETALLA_AUXILIARES"                    => "Detalla auxiliares",
    "DETALLA_TERCEROS"                      => "Detalla terceros",
    "AYUDA_DETALLA_AUXILIARES"              => "Permite generar el balance detallando las cuentas auxiliares",
    "AYUDA_DETALLA_TERCEROS"                => "Permite generar el balance detallando los terceros",
    "FECHA"                                 => "Fecha",
    "IMRPIMIR_PDF"                          => "Imprimir",

    "BALANCE_GENERAL"                       => "Balance general",
    "BALANCE_PERDIDAS_GANANCIAS"            => "Balance de perdidas y ganancias",
    "FECHA_DESDE"                           => "Fecha desde",
    "FECHA_HASTA"                           => "Fecha hasta",
    "TOTAL"                                 => "Total",

    "CODIGO"                                => "Código",
    "NOMBRE_CUENTA"                         => "Cuenta",
    "DEBE"                                  => "Debe",
    "HABER"                                 => "Haber",

    "GRUPO"                                 => "Grupo",
    "SUBGRUPO"                              => "Subgrupo",
    "CUENTA"                                => "Cuenta",
    "CUENTA_AUXILIAR"                       => "Subcuenta",
    "NIVEL_DETALLE"                         => "Nivel de detalle",
    "AYUDA_NIVEL_DETALLE"                   => "Nivel de detalle por el cúal será generado el formulario",

    "TERCERO"                               => "Tercero",
    "FECHA_CONTABILIZACION"                 => "Fecha contabilización",
    "COMPROBANTE"                           => "Comprobante No.",
    "SUCURSAL_GENERA"                       => "Almacen genera",
    "SUCURSAL_CONTABILIZA"                  => "Almacen contabiliza",
    "TIPO_COMPROBANTE"                      => "Tipo comprobante",
    "AYUDA_TIPO_COMPROBANTE"                => "Seleccione el tipo comprobante para el movimiento",
    "NUMERO_COMPROBANTE"                    => "No. de comprobante",
    "AYUDA_NUMERO_COMPROBANTE"              => "Digite el No. de comprobante",
    "TERCERO"                               => "Tercero",
    "FECHA_CONTABILIZACION"                 => "Fecha de contabilización",
    "TIPO_DOCUMENTO"                        => "Tipo de documento",
    "AYUDA_TIPO_DOCUMENTO"                  => "Seleccione el tipo de documento para el movimiento",
    "CONSECUTIVO_DOCUMENTO"                 => "Número documento",
    "FECHA_DOCUMENTO"                       => "Fecha del documento",
    "CUENTA_BANCARIA"                       => "Cuenta bancaria",
    "CONSECUTIVO_CHEQUE"                    => "Consecutivo cheque",
    "VALOR"                                 => "Valor",
    "CANTIDAD_VENCIMIENTOS"                 => "Cuotas",
    "CUENTA"                                => "Cuenta",
    "SENTIDO"                               => "Sentido",
    "AUXILIAR_CONTABLE"                     => "Auxiliar contable",
    "TERCERO_CUENTA"                        => "Tercero cuenta",
    "TIPO_DOCUMENTO_SOPORTE"                => "Tipo de documento cruce",
    "AYUDA_TIPO_DOCUMENTO_SOPORTE"          => "Seleccione el tipo de documento cruce para el movimiento",
    "NUMERO_DOCUMENTO_SOPORTE"              => "Número documento cruce",
    "TIPO_DOCUMENTO_BANCARIO"               => "Tipo de documento bancario",
    "NUMERO_DOCUMENTO_BANCARIO"             => "Número documento bancario",
    "TERCERO_FIADOR1"                       => "Tercero fiador 1",
    "TERCERO_FIADOR2"                       => "Tercero fiador 2",
    "TITULO_SENTIDO"                        => "Sentido de la Cuenta",
    "FECHA_VENCIMIENTO"                     => "Fecha vencimiento",
    "VALOR_VENCIMIENTO"                     => "Valor cuota",
    "INTERVALO"                             => "Intervalo (Días)",
    "OPCIONES"                              => "Opciones",
    "TIPO_DOCUMENTO_CRUCE"                  => "Docto Cruce",
    "NUMERO_DOCUMENTO_CRUCE"                => "Numero Cruce",
    "SALDOS"                                => "Saldos",
    "DEBITO"                                => "Debito",
    "CREDITO"                               => "Credito",
    "DOCUMENTO_SALDO"                       => "Abonar a documento",
    "AYUDA_DOCUMENTO_SALDO"                 => "Seleccione el documento a Abonar",
    "SUCURSAL"                              => "Almacen",
    "TOTAL_DEBITO"                          => "Total débito",
    "TOTAL_CREDITO"                         => "Total crédito",
    "NUM"                                   => "No.",
    "DEBITOS"                               => "Débitos",
    "CREDITOS"                              => "Créditos",
    "ELIMINAR_ITEM"                         => "Eliminar ítem",
    "MODIFICAR_ITEM"                        => "Modificar ítem",
    "SALDO"                                 => "Saldo",
    "TOTAL_SALDO"                           => "Total saldo",
    "OTROS"                                 => "Otros",
    "ABONOS"                                => "Saldos con abonos asignados",
    "CHEQUE"                                => "Cheque",
    "ABONO_DOCUMENTO"                       => "Abono a documento:",
    "SALDO_TOTAL"                           => "- Saldo total: $",
    "ESTADO"                                => "Estado",
    "ACTIVO"                                => "Activo",
    "ANULADO"                               => "Anulado",
    "OBSERVACIONES"                         => "Observaciones",

    "IMPRIMIR_PDF"                          => "[Imprimir]",
    "TERCERO_UBICACION"                     => "Ubicación",
    "TERCERO_DIRECCION"                     => "Dirección",
    "TERCERO_TELEFONO"                      => "Teléfono",

    "REPORTES"                              => "Reportes",
    "FECHA_BALANCE_GENERAL"                 => "Fecha balance",
    "FECHA_INICIAL_PYG"                     => "Fecha desde",
    "FECHA_FINAL_PYG"                       => "Fecha hasta",
    "GENERAR"                               => "Generar",
    "VALOR_BASE1"                           => "Valor base 1",
    "AYUDA_VALOR_BASE1"                     => "Debe ingresar el valor base 1",
    "VALOR_BASE2"                           => "Valor base 2",
    "AYUDA_VALOR_BASE2"                     => "Debe ingresar el valor base 2",

    "AYUDA_SUCURSAL_GENERA"                 => "Almacen donde se genera el movimiento contable",
    "AYUDA_SUCURSAL_CONTABILIZA"            => "Almacen donde se contabilizará el movimiento contable",
    "AYUDA_TERCERO"                         => "Tercero al cual se le causa el movimiento",
    "AYUDA_FECHA_CONTABILIZACION"           => "Fecha en que sera contabilizado el saldo",
    "AYUDA_CONSECUTIVO_DOCUMENTO"           => "Número del documento que genera el saldo",
    "AYUDA_FECHA_DOCUMENTO"                 => "Fecha del documento que genera el saldo",
    "AYUDA_CONSECUTIVO_CHEQUE"              => "Número del cheque que genera el documento",
    "AYUDA_VALOR"                           => "Valor del saldo",
    "AYUDA_CANTIDAD_VENCIMIENTOS"           => "Cantidad de vencimientos que aplicarán al saldo",
    "AYUDA_CUENTA"                          => "Cuenta del plan contable a la que afecta el saldo",
    "AYUDA_SENTIDO"                         => "Sentido de la transacción",
    "AYUDA_AUXILIAR_CONTABLE"               => "Auxiliar contable que aplica para la cuenta seleccionada",
    "AYUDA_TERCERO_CUENTA"                  => "Tercero que es afectado por la cuenta",
    "AYUDA_NUMERO_DOCUMENTO_SOPORTE"        => "Número del documento que sirve de soporte",
    "AYUDA_NUMERO_DOCUMENTO_BANCARIO"       => "Número del documento que sirve de bancario",
    "AYUDA_TERCERO_FIADOR1"                 => "Tercero 1 que sirve de fiador para el saldo",
    "AYUDA_TERCERO_FIADOR2"                 => "Tercero 2 que sirve de fiador para el saldo",
    "AYUDA_INTERVALO"                       => "Intervalo de días a aplicar entre cuotas",
    "AYUDA_TOTAL_DEBITO"                    => "Total débito",
    "AYUDA_TOTAL_CREDITO"                   => "Total crédito",
    "AYUDA_FECHA_BALANCE_GENERAL"           => "Fecha del balance general",
    "AYUDA_FECHA_INICIAL_PYG"               => "Fecha inicial del balance de PYG",
    "AYUDA_FECHA_FINAL_PYG"                 => "Fecha final del balance de PYG",
    "AYUDA_OBSERVACIONES"                   => "Observaciones adicionales para el movimiento contable",

    "ERROR_ITEM_ANULADO"                    => "La operación no se puede realizar debido a que el movimiento ya fue anulado",
    "ERROR_ANULAR_CRUCE"                    => "La operación no se puede realizar debido a que el movimiento posee cruce de documentos",
    "ERROR_ANULAR_AUTO"                     => "La operación no se puede realizar debido a que el movimiento tiene documento con manejo automatico",
    "ERROR_ANULAR_CHEQUE"                   => "La operación no se puede realizar debido a que el movimiento generó cheques",
    "ERROR_CUENTA_CHEQUE"                   => "Se requiere la cuenta contable a la que se asignara el cheque generado",
    "ERROR_CUENTA"                          => "La cuenta que esta ingresando no esta validada en el Plan contable",
    "PERIODOS_CONTABLES"                    => "Periodos contables",

    "RANGO_DIAS"                            => "Rango de días",
    "AYUDA_RANGO_DIAS"                      => "Rango de días por el cúal quiere ser generado el informe",
    "30_DIAS"                               => "30 días",
    "60_DIAS"                               => "60 días",
    "90_DIAS"                               => "90 días",
    "ERROR_GENERAR_ARCHIVO"                 => "No hay datos para generar el archivo",
    "CUADRE"                                => "Cuadre",
    "CONSOLIDAR"                            => "(Consolidar)",
    "ESTADO_1"                              => "Documento descuadrado",
    "ESTADO_0"                              => "Documento cuadrado",
    "MENSAJE_PERIODO_CONTABLE"              => "Este almacen tiene actualmente el periodo contable cerrado para esta operación",

    "DATOS_MOVIMIENTO_INCOMPLETO"           => "Debe datos para el movimiento",
    "TERCERO_VACIO"                         => "Debe ingresar un tercero valido y no vacio",
    "TIPO_DOCUMENTO_VACIO"                  => "Debe ingresar un tipo de documento",
    "DOCUMENTO_SOPORTE_VACIO"               => "Debe ingresar un numero de documento cruce",
    "CONSECUTIVO_DOCUMENTO_VACIO"           => "Debe ingresar un numero de documento",
    "TIPO_COMPROBANTE_VACIO"                => "Debe ingresar un tipo de comprobante",
    "NUMERO_COMPROBANTE_VACIO"              => "Debe ingresar un numero de comprobante",
    "CUENTA_VACIO"                          => "Debe ingresar una cuenta contable",
    "INGRESAR_CUENTA"                       => "Por favor digite la cuenta que afecta la transaccion",
    "ERROR_DATOS_MOVIMIENTO_INCOMPLETOS"    => "Debe ingresar los datos de la pestaña de movimiento",
    "VALOR_VACIO"                           => "Debe ingresar un valor",
    "VALOR_INCORRECTO"                      => "El valor ingresado es mayor al valor del saldo al que intenta abonar",

    "ERROR_NO_SALDOS"                       => "Error, no existen saldos pendientes para esta cuenta",
    "CUOTAS_VACIA"                          => "Cantidad de cuotas invalida",
    "INTERVALOS_VACIO"                      => "Cantidad de intervalos invalida",
    "INTERVALOS_INVALIDOS"                  => "Cantidad de intervalos no puede quedar en cero para esa cantidad de cuotas",

    "ERROR_TABLAS_VACIAS"                   => "Error, las siguientes tablas requieren datos para generar un movimiento\n\n",
    "ERROR_TABLA_VACIA_SUCURSALES"          => "- Almacenes\n",
    "ERROR_TABLA_VACIA_TIPOS_COMPROBANTES"  => "- Tipos de comprobantes\n",
    "ERROR_TABLA_VACIA_TIPOS_DOCUMENTOS"    => "- Tipos de documentos\n",
    "ERROR_TABLA_VACIA_TIPOS_CUENTAS"       => "- Plan contale (Cuentas de movimiento)\n",
    "ERROR_TABLA_VACIA_TABLAS"              => "- Tablas (Nombre de la tabla : movimientos_contables)\n",
    "CUENTAS_BANCARIAS_VACIAS"              => "El tipo de documento seleccionado genera cheques y no existen cuentas bancarias\npara este documento en el almacen que genera seleccionada.\nFavor verifique",
    "TOTALES"                               => "Totales",
    "ITEM_ANULADO"                          => "Movimiento anulado satisfactoriamente",
    "ERROR_EXISTE_CUENTA"                   => "Los datos de la cabecera del movimiento se repiten en otro movimiento,\n Favor verifique la informacion",

    "DOCUMENTO_BANCARIO"                    => "Documento Bancario",
    "BANCO"                                 => "Banco",
    "NUMERO_CUENTA"                         => "No. Cuenta",
    "CONSECUTIVO"                           => "Consecutivo",
    "NUMERO"                                => "No.",
    "PAGINA"                                => "Pagina",
    "ERROR_EXISTE_CONSECUTIVO"              => "Error, Hoy ya se ha registrado un movimiento en este almacen con el mismo  tipo y numero de documento",
    "ERROR_EXISTE_FECHA"                    => "Ya existe una fecha igual para la cuota, verifique",
    "DENEGADO_REGISTRO_CUENTA"              => "Error, no se permite la misma cuenta con sentidos diferentes en el registro.",
    "DENEGADO_REGISTRO_CUENTA2"             => "Error, no se permite dos saldos de la misma cuenta en el mismo movimiento.",
    "ERROR_SUCURSALES_VACIAS"               => "Error no existen almacenes en el sistema para generar el reporte",

    "REPODIMD"                              => "Diario de movimientos por documento",
    "REPODIMC"                              => "Diario de movimientos por comprobante",
    "SELECCIONAR_TODOS"                     => "Seleccionar todos",
    "CONSOLIDAR_EN"                         => "Consolidar en",
    "FECHA_DESDE"                           => "Fecha desde",
    "FECHA_HASTA"                           => "Fecha hasta",
    "RANGO_FECHAS"                          => "Seleccione el rango de fechas",
    "MOSTRAR_DETALLE"                       => "Mostrar detalle",
    "PESTANA_SUCURSALES"                    => "Almacenes",
    "TIPO_COMPROBANTE"                      => "Tipo comprobante",
    "CONSOLIDADAS"                          => "Consolidadas",
    "DIFERENCIA"                            => "Diferencia",
    "TOTAL_COMPROBANTE"                     => "Total Comprobante",
    "TOTAL_SUCURSAL"                        => "Total almacen",
    "TOTAL_EMPRESA"                         => "Total empresa",
    "CUENTA_MAYOR"                          => "Mayor",
    "AYUDA_SUCURSAL_PRINCIPAL"              => "Almacen por donde se genera el reporte ",
    "AYUDA_SUCURSAL_CONSOLIDA"              => "Seleccione el almacen que desea consolidar en el reporte ",
    "SUCURSAL_VACIO"                        => "Debe seleccionar un almacen",
    "DOCUMENTO_FECHA"                       => "Doc. Fecha",
    "DOCUMENTO_CONSECUTIVO"                 => "Doc. No.",
    "ERROR_GENERAR_ARCHIVO"                 => "No hay datos para generar el archivo",
    "DOCUMENTO"                             => "Documento",
    "COMPROBANTE"                           => "Comprobante",
    "ANEXO"                                 => "Anexo",
    "AUXILIAR"                              => "Aux"
);
?>
