<?php
/**
*
* Copyright (C) 2020 Jobdaily
* Raul Mauricio Oidor Lozano <ozzymauricio75@gmail.com>
*
* Este archivo es parte de:
* Jobdaily:: Sofware empresarial a la medida
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los terminos de la Licencia Publica General GNU
* publicada por la Fundacion para el Software Libre, ya sea la version 3
* de la Licencia, o (a su eleccion) cualquier version posterior.
*
* Este programa se distribuye con la esperanza de que sea util, pero
* SIN GARANTIA ALGUNA; ni siquiera la garantia implicita MERCANTIL o
* de APTITUD PARA UN PROPOSITO DETERMINADO. Consulte los detalles de
* la Licencia Publica General GNU para obtener una informacion mas
* detallada.
*
* Deberia haber recibido una copia de la Licencia Publica General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(
    "REPOSCXC"                              => "Saldos cuentas por cobrar",
    "REPOSCXP"                              => "Saldos cuentas por pagar",
    "REPOSMDO"                              => "Saldos de movimientos por documento",

    "PESTANA_GENERAL"                       => "General",
    "PESTANA_MOVIMIENTOS"                   => "Movimientos",
    "PESTANA_BALANCE_COMPROBACION"          => "Balance de comprobación",
    "PESTANA_BALANCE_GENERAL"               => "Balance general",
    "PESTANA_PYG"                           => "Perdidas y ganancias",
    "DETALLA_AUXILIARES"                    => "Detalla auxiliares",
    "DETALLA_TERCEROS"                      => "Detalla terceros",
    "AYUDA_DETALLA_AUXILIARES"              => "Permite generar el balance detallando las cuentas auxiliares",
    "AYUDA_DETALLA_TERCEROS"                => "Permite generar el balance detallando los terceros",
    "FECHA"                                 => "Fecha",
    "IMRPIMIR_PDF"                          => "Imprimir",

    "BALANCE_GENERAL"                       => "Balance general",
    "CUENTAS_POR_PAGAR"                     => "Saldos cuentas por pagar",
    "CUENTAS_POR_COBRAR"                    => "Saldos cuentas por cobrar",
    "BALANCE_PERDIDAS_GANANCIAS"            => "Balance de perdidas y ganancias",
    "FECHA_DESDE"                           => "Fecha desde",
    "FECHA_HASTA"                           => "Fecha hasta",
    "TOTAL"                                 => "Total",
    "TOTAL_SALDOS"                          => "Total saldos",

    "CODIGO"                                => "Código",
    "NOMBRE_CUENTA"                         => "Cuenta",
    "DEBE"                                  => "Debe",
    "HABER"                                 => "Haber",

    "GRUPO"                                 => "Grupo",
    "SUBGRUPO"                              => "Subgrupo",
    "CUENTA"                                => "Cuenta",
    "CUENTA_AUXILIAR"                       => "Subcuenta",
    "NIVEL_DETALLE"                         => "Nivel de detalle",
    "AYUDA_NIVEL_DETALLE"                   => "Nivel de detalle pro el cúal será generado el formulario",

    "TERCERO"                               => "Tercero",
    "FECHA_CONTABILIZACION"                 => "Fecha contabilización",
    "COMPROBANTE"                           => "Comprobante No.",
    "SUCURSAL_GENERA"                       => "Almacen genera",
    "SUCURSAL_CONTABILIZA"                  => "Almacen contabiliza",
    "TIPO_COMPROBANTE"                      => "Tipo comprobante",
    "NUMERO_COMPROBANTE"                    => "Número de comprobante",
    "TERCERO"                               => "Tercero",
    "FECHA_CONTABILIZACION"                 => "Fecha de contabilización",
    "TIPO_DOCUMENTO"                        => "Tipo de documento",
    "CONSECUTIVO_DOCUMENTO"                 => "Número documento",
    "FECHA_DOCUMENTO"                       => "Fecha del documento",
    "CUENTA_BANCARIA"                       => "Cuenta bancaria",
    "CONSECUTIVO_CHEQUE"                    => "Consecutivo cheque",
    "VALOR"                                 => "Valor",
    "CANTIDAD_VENCIMIENTOS"                 => "Cuotas",
    "CUENTA"                                => "Cuenta",
    "SENTIDO"                               => "Sentido",
    "AUXILIAR_CONTABLE"                     => "Auxiliar contable",
    "TERCERO_CUENTA"                        => "Tercero cuenta",
    "TIPO_DOCUMENTO_SOPORTE"                => "Tipo de documento cruce",
    "NUMERO_DOCUMENTO_SOPORTE"              => "Número documento cruce",
    "TIPO_DOCUMENTO_BANCARIO"               => "Tipo de documento bancario",
    "NUMERO_DOCUMENTO_BANCARIO"             => "Número documento bancario",
    "TERCERO_FIADOR1"                       => "Tercero fiador 1",
    "TERCERO_FIADOR2"                       => "Tercero fiador 2",

    "DATOS_SALDO"                           => "Datos del Saldo",
    "FECHA_POR_VENCER"                      => "Cartera Por Vencer",
    "FECHA_VENCIDA"                         => "Cartera Vencida",
    "VALOR_VENCIMIENTO"                     => "Valor cuota",
    "FECHA_VENCIMIENTO"                     => "Fecha vencimiento",
    "FECHA_MAYOR_30"                        => "Mayor 30",
    "FECHA_1_30"                            => "1 - 30",
    "FECHA_0_30"                            => "0 - 30",
    "FECHA_31_60"                           => "31 - 60",
    "FECHA_61_90"                           => "61 - 90",
    "FECHA_MAYOR_90"                        => "Mayor 90",

    "INTERVALO"                             => "Intervalo (Días)",
    "OPCIONES"                              => "Opciones",
    "SALDOS"                                => "Saldos",
    "DEBITO"                                => "Db",
    "CREDITO"                               => "Cr",
    "DOCUMENTO_SALDO"                       => "Abonar a documento",
    "SUCURSAL"                              => "Almacen",
    "TOTAL_DEBITO"                          => "Total débito",
    "TOTAL_CREDITO"                         => "Total crédito",
    "NUM"                                   => "No.",
    "DEBITOS"                               => "Débitos",
    "CREDITOS"                              => "Créditos",
    "ELIMINAR_ITEM"                         => "Eliminar ítem",
    "MODIFICAR_ITEM"                        => "Modificar ítem",
    "SALDO"                                 => "Saldo",
    "TOTAL_SALDO"                           => "Total saldo",
    "OTROS"                                 => "Otros",
    "ABONOS"                                => "Saldos con abonos asignados",
    "CHEQUE"                                => "Cheque",
    "ABONO_DOCUMENTO"                       => "Abono a documento:",
    "SALDO_TOTAL"                           => "- Saldo total: $",
    "ESTADO"                                => "Estado",
    "ACTIVO"                                => "Activo",
    "ANULADO"                               => "Anulado",

    "IMPRIMIR_PDF"                          => "[Imprimir]",
    "TERCERO_UBICACION"                     => "Ubicación",
    "TERCERO_DIRECCION"                     => "Dirección",
    "TERCERO_TELEFONO"                      => "Teléfono",

    "REPORTES"                              => "Reportes",
    "FECHA_BALANCE_GENERAL"                 => "Fecha balance",
    "FECHA_INICIAL_PYG"                     => "Fecha desde",
    "FECHA_FINAL_PYG"                       => "Fecha hasta",
    "GENERAR"                               => "Generar",

    "AYUDA_SUCURSAL_GENERA"                 => "Almacen donde se generó el movimiento contable",
    "AYUDA_SUCURSAL_CONTABILIZA"            => "Almacen donde se contabilizará el movimiento contable",
    "AYUDA_TERCERO"                         => "Tercero al que se le aplicara el saldo",
    "AYUDA_FECHA_CONTABILIZACION"           => "Fecha en que sera contabilizado el saldo",
    "AYUDA_CONSECUTIVO_DOCUMENTO"           => "Número del documento que genera el saldo",
    "AYUDA_FECHA_DOCUMENTO"                 => "Fecha del documento que genera el saldo",
    "AYUDA_CONSECUTIVO_CHEQUE"              => "Número del cheque que genera el documento",
    "AYUDA_VALOR"                           => "Valor del saldo",
    "AYUDA_CANTIDAD_VENCIMIENTOS"           => "Cantidad de vencimientos que aplicarán al saldo",
    "AYUDA_CUENTA"                          => "Cuenta del plan contable a la que afecta el saldo",
    "AYUDA_SENTIDO"                         => "Sentido de la transacción",
    "AYUDA_AUXILIAR_CONTABLE"               => "Auxiliar contable que aplica para la cuenta seleccionada",
    "AYUDA_TERCERO_CUENTA"                  => "Tercero que es afectado por la cuenta",
    "AYUDA_NUMERO_DOCUMENTO_SOPORTE"        => "Número del documento que sirve de soporte",
    "AYUDA_NUMERO_DOCUMENTO_BANCARIO"       => "Número del documento que sirve de bancario",
    "AYUDA_TERCERO_FIADOR1"                 => "Tercero 1 que sirve de fiador para el saldo",
    "AYUDA_TERCERO_FIADOR2"                 => "Tercero 2 que sirve de fiador para el saldo",
    "AYUDA_INTERVALO"                       => "Intervalo de días a aplicar entre cuotas",
    "AYUDA_TOTAL_DEBITO"                    => "Total débito",
    "AYUDA_TOTAL_CREDITO"                   => "Total crédito",
    "AYUDA_FECHA_BALANCE_GENERAL1"          => "Primer fecha hasta la cual se genera el balance general",
    "AYUDA_FECHA_BALANCE_GENERAL2"          => "Segunda fecha hasta la cual se genera el balance general",
    "AYUDA_FECHA_BALANCE_GENERAL3"          => "Tercera fecha hasta la cual se genera el balance general",
    "AYUDA_FECHA_INICIAL_PYG"               => "Fecha inicial del balance de PYG",
    "AYUDA_FECHA_FINAL_PYG"                 => "Fecha final del balance de PYG",

    "ERROR_ITEM_ANULADO"                    => "La operación no se puede realizar debido a que el elemento se encuentra anulado",
    "ERROR_ANULAR_OTROS"                    => "La operación no se puede realizar debido a que el elemento posee cruce de documentos",
    "ERROR_CUENTA_CHEQUE"                   => "Se requiere la cuenta contable a la que se asignara el cheque generado",
    "PERIODOS_CONTABLES"                    => "Periodos contables",

    "RANGO_DIAS"                            => "Rango de días",
    "AYUDA_RANGO_DIAS"                      => "Rango de días por el cúal quiere ser generado el informe",
    "30_DIAS"                               => "30 días",
    "60_DIAS"                               => "60 días",
    "90_DIAS"                               => "90 días",
    "ERROR_GENERAR_ARCHIVO"                 => "No hay datos para generar el archivo",

    "BALANCE_PYG"                           => "Balance PYG",
    "BALANCE_COMPROBACION"                  => "Balance comprobación",
    "BALANCE_MAYOR_BALANCE"                 => "Mayor y balance",
    "BALANCE_ESTADO_CUENTA"                 => "Estado de cuenta",
    "GESTBALC"                              => "Balances",

    "REPOBALC"                              => "Balance general",
    "REPOBPYG"                              => "Balance de perdidas y ganancias",
    "REPOBACO"                              => "Balance de comprobación",
    "REPOESCU"                              => "Estado de cuenta",
    "REPOMABA"                              => "Mayor y balance",
    "UTILIDAD_EJERCICIO"                    => "Utilidad del ejercicio",
    "BALANCE_COMPROBACION"                  => "Balance de comprobación",
    "PESTANA_ESTADO_CUENTA"                 => "Estado de cuenta",
    "ESTADO_CUENTA"                         => "Estado de cuenta",
    "SALDO_INICIAL"                         => "Saldo inicial",
    "MOVIMIENTO_DEBE"                       => "Mov debito",
    "MOVIMIENTO_HABER"                      => "Mov crédito",
    "SALDO_ACTUAL"                          => "Saldo actual",
    "CUENTA_INICIAL"                        => "Cuenta inicial",
    "CUENTA_FINAL"                          => "Cuenta final",
    "AYUDA_CUENTA_INICIAL"                  => "Es la cuenta de donde se quiere inciar el informe",
    "AYUDA_CUENTA_FINAL"                    => "Es la cuenta donde culmina el informe contable",
    "CUENTA_MAYOR"                          => "Mayor",
    "VARIACION"                             => "Variación",
    "PORCENTAJE"                            => "%",
    "TODO_PLAN_CONTABLE"                    => "Seleccionar todo el plan contable",
    "AYUDA_TODO_PLAN_CONTABLE"              => "Permite escojer el rango de cuentas por el cual desea ser generado el informe",
    "PESTANA_SUCURSALES"                    => "Almacenes",
    "SELECCIONAR_TODOS"                     => "Seleccionar todos",
    "CUADRE"                                => "Cuadre",
    "ESTADO_0"                              => "",
    "ESTADO_1"                              => "Documento descuadrado",
    "CONSOLIDAR"                            => "(Consolidar)",
    "CONSOLIDADO"                           => "Consolidado",

    /*** Balance CXC ***/
    "PESTANA_BALANCE_CXC"                   => "Reporte cuenta por cobrar",
    "CUENTA_POR_COBRAR"                     => "Cuentas por cobrar",
    "FECHA_SALDO"                           => "Fecha de corte:",
    "AYUDA_FECHA_SALDO"                     => "Seleccione la fecha de corte para el reporte",
    "ERROR_PRIVILEGIOS_USUARIO"             => "Usuario sin privilegios para este componente",

    /***  SALDO_MOVIMIENTO_DOCUMENTO ***/
    "BALANCE_SALDOS_MOVIMIENTOS_DOCUMENTO"  => "Reporte de Saldos movimiento por documento",
    "SALDO_MOVIMIENTO_DOCUMENTO"            => "Saldo movimiento documento",
    "FECHA_DESDE"                           => "Fecha desde",
    "AYUDA_FECHA_DESDE"                     => "Seleccione la fecha desde donde inicia el reporte",
    "FECHA_HASTA"                           => "Fecha hasta",
    "AYUDA_FECHA_HASTA"                     => "Seleccioa la fecha final para el reporte",
    "CUENTA_DESDE"                          => "Cuenta desde",
    "AYUDA_CUENTA_DESDE"                    => "Seleccione la cuenta donde inicia el reporte",
    "CUENTA_HASTA"                          => "Cuenta hasta",
    "AYUDA_CUENTA_HASTA"                    => "Seleccione la cuenta donde finaliza el reporte",
    "NIT_DESDE"                             => "Nit desde",
    "AYUDA_NIT_DESDE"                       => "Digite el tercero para el reporte",
    "NIT_HASTA"                             => "Nit hasta",
    "AYUDA_NIT_HASTA"                       => "Seleccione el nit donde finaliza el reporte",
    "DOCUMENTO_DESDE"                       => "Tipo documento",
    "AYUDA_DOCUMENTO_DESDE"                 => "Seleccione el tipo de documento para el reporte",
    "DOCUMENTO_HASTA"                       => "Tipo documento hasta",
    "AYUDA_DOCUMENTO_HASTA"                 => "Seleccione el tipo de documento donde finaliza el reporte",
    "MOSTRAR_SALDO_CERO"                    => "Mostrar saldos en cero",
    "MOSTRAR_SALDO_DETALLE"                 => "Mostrar detalle",
    "TERCERO_VACIO"                         => "Debe ingresar el tercero",
    "SUCURSAL_VACIO"                        => "Debe seleccionar un almacen",
    "NUMEROS_VACIO"                         => "Debe ingresar el numero desde y el numero hasta",
    "CUENTA_DESDE_VACIO"                    => "Debe seleccionar la cuenta desde",
    "CUENTA_HASTA_VACIO"                    => "Debe seleccionar la cuenta hasta",
    "FECHA_DESDE_VACIO"                     => "Debe seleccionar la fecha desde",
    "FECHA_HASTA_VACIO"                     => "Debe seleccionar la fecha hasta",

    "ID_PLAN_CONTABLE"                      => "Codigo contable",
    "SALDOS"                                => "Valor vencimiento",
    "ABONOS"                                => "Abonos",
    "SALDO_PARCIAL"                         => "Saldo parcial",
    "NUMERO_CUOTA"                          => "Cuota #",
    "VALOR_CUOTA"                           => "Valor cuota",
    "DOCUMENTO_ABONO"                       => "Documento cruce",
    "AUXILIAR_CONTABLE"                     => "Auxiliar contable",
    "NUMERO_DOCUMENTO"                      => "Numero documento",
    "NUMERO_FACTURA"                        => "Documento",
    "VALOR_FACTURA"                         => "Valor de la factura",
    "TIPO_COMPROBANTE"                      => "Comprobante",
    "SALDO_TOTAL"                           => "Saldo Total",
    "SELECCIONAR_TODOS_TERCEROS"            => "Buscar todos los terceros",
    "AYUDA_SELECCIONAR_TODOS"               => "Incluir en el reporte todos los terceros",
    "SELECCIONAR_TODOS_DOCUMENTOS"          => "Buscar todos los documentos",
    "AYUDA_SELECCIONAR_TODOS_DOCUMENTOS"    => "Incluir en el reporte todos los documentos",
    "SELECCIONAR_TODOS_CONSECUTIVOS"        => "Buscar todos los consecutivos",
    "AYUDA_SELECCIONAR_TODOS_CONSECUTIVOS"  => "Incluir en el reporte todos los consecutivos",
    "AYUDA_SUCURSAL_PRINCIPAL"              => "Almacen por donde se genera el reporte ",
    "AYUDA_SUCURSAL_CONSOLIDA"              => "Seleccione el almacen que desea consolidar en el reporte ",
    "ERROR_FECHAS"                          => "La fecha desde debe ser mayor a la fecha hasta",
    "ERROR_CUENTAS"                         => "La cuenta desde debe ser mayor a la cuenta hasta",
    "ERROR_NUMEROS"                         => "El numero desde debe ser mayor al numero hasta",
    "ERROR_SIN_DATOS"                       => "No se encontraron datos para generar el reporte",
    "ERROR_SUCURSALES"                      => "Error, seleccione por lo menos un almacen",
    "FECHAS_REPORTE"                        => "Fecha del reporte",
    "CUENTAS_REPORTE"                       => "Cuentas del reporte",
    "NUMERO_DESDE"                          => "Numero desde",
    "AYUDA_NUMERO_DESDE"                    => "Digite el Numero de documento desde",
    "NUMERO_HASTA"                          => "Numero hasta",
    "AYUDA_NUMERO_HASTA"                    => "Digite el Numero de documento hasta",
    "OBSERVACIONES"                         => "Observaciones",
    "AYUDA_OBSERVACIONES"                   => "Visualiazar las observaciones",
    "DETALLE"                               => "Detalle",

    /*** Diario de movimientos por documento - comprobante ***/
    "NUMERO_COMPROBANTE_DESDE"              => "No. comprobante desde",
    "NUMERO_COMPROBANTE_HASTA"              => "No. comprobante hasta",
    "NUMERO_DOCUMENTO_DESDE"                => "No. documento desde",
    "NUMERO_DOCUMENTO_HASTA"                => "No. documento hasta",
    "MOSTRAR_DETALLE"                       => "Mostrar detalle",
    "CONSOLIDAR_EN"                         => "Consolidar en",
    "CONSOLIDADAS"                          => "Consolidadas",
    "DIFERENCIA"                            => "Diferencia",
    "TERCERO_DOCUMENTO"                     => "Tercero",
    "DOCUMENTO_FECHA"                       => "Doc. Fecha",
    "DOCUMENTO_CONSECUTIVO"                 => "Doc. No.",
    "TOTAL_SUCURSAL"                        => "Total almacen",
    "TOTAL_DOCUMENTO"                       => "Total documento",
    "TOTAL_COMPROBANTE"                     => "Total Comprobante",
    "SALDO_ANTERIOR"                        => "Saldo anterior",
    "SALDO_DEBITO"                          => "Débito",
    "SALDO_CREDITO"                         => "Crédito",
    "TOTAL"                                 => "Total",
    "MENSAJE_EXITO"                         => "Archivo generado satisfactoriamente",
    "PASIVO"                                => "Pasivo",
    "PATRIMONIO"                            => "Patrimonio",
    "RESULTADO"                             => "Resultado",
    "INGRESOS"                              => "Ingresos",
    "GASTOS"                                => "Gastos",
    "COSTOS"                                => "Costos",
    "MENSAJE_NO_GENERA_PDF"                 => "No se genero información",
    "SALDO_INICIAL"                         => "Saldo inicial",
    "SALDO_FINAL"                           => "Saldo final",
    "ERROR_CUENTA_FINAL"                    => "Por favor seleccione una cuenta final",
    "NUMERO"                                => "Numero",
    "ERROR_CUENTA_INICIAL"                  => "La cuenta inicial no puede ser mayor que la cuenta final",
    "SALDO_INICIAL_CUENTA"                  => "Saldo inicial codigo contable ",
    "TOTAL_CODIGO"                          => "Total codigo contable ",
    "TOTAL_AUXILIAR"                        => "Total auxiliar",
    "TOTAL_TERCERO"                         => "Total tercero",
    "TOTAL_EMPRESA"                         => "Total empresa",
    "VALOR_ABONO"                           => "Valor de Abono",
    "TOTAl_ABONO"                           => "Total Abono",
    "HASTA_FECHA"                           => "hasta la fecha",
    "FECHAS"                                => "Seleccione el rango de fechas",

    "ERROR_SUCURSALES_VACIAS"               => "Error, no existen almacenes creados. Favor verifique",

    "ERROR_TABLAS_VACIAS"                   => "Error, las siguientes tablas requieren datos para generar el reporte\n\n",
    "ERROR_TABLA_VACIA_SUCURSALES"          => "- Almacenes\n",
    "ERROR_TABLA_VACIA_PLAN_CONTABLE"       => "- Plan Contable (Cuentas que manejen saldos y terceros)\n",
    "ERROR_TABLA_VACIA_TIPOS_DOCUMENTOS"    => "- Tipos de documentos\n"
)
?>
