<?php

/**
*
* Copyright (C) 2020 Jobdaily
* Raul Mauricio Oidor Lozano <ozzymauricio75@gmail.com>
* 
*
* Este archivo es parte de:
* Jobdaily:: Sofware empresarial a la medida
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los términos de la Licencia Pública General GNU
* publicada por la Fundación para el Software Libre, ya sea la versión 3
* de la Licencia, o (a su elección) cualquier versión posterior.
*
* Este programa se distribuye con la esperanza de que sea útil, pero
* SIN GARANTÍA ALGUNA; ni siquiera la garantía implícita MERCANTIL o
* de APTITUD PARA UN PROPÓSITO DETERMINADO. Consulte los detalles de
* la Licencia Pública General GNU para obtener una información más
* detallada.
*
* Debería haber recibido una copia de la Licencia Pública General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(
    "PESTANA_TERCERO"                => "Identificación",
    "PESTANA_TRIBUTARIA"             => "Tributaria",
    "GESTPROV"                       => "Proveedores",
    "DOCUMENTO_ENTIDAD" 	         => "Documento de identidad",
    "ENTIDAD"			             => "Entidad",
    "ADICPROV"                       => "Adicionar proveedores",
    "CONSPROV"                       => "Cosultar proveedores",
    "MODIPROV"                       => "Modificar proveedores",
    "ELIMPROV"                       => "Eliminar proveedores",
    "DOCUMENTO_PROVEEDOR"            => "Documento de identidad",
    "PROVEEDOR"                      => "Nombre ó razón social",
    "TIPO_DOCUMENTO_IDENTIDAD"       => "Tipo de documento de identidad",
    "AYUDA_TIPO_DOCUMENTO"           => "Seleccione el tipo de documento de identidad",
    "TIPO_PERSONA"                   => "Tipo de persona",
    "PERSONA_NATURAL"                => "Persona natural",
    "PERSONA_JURIDICA"               => "Persona juridica",
    "CODIGO_INTERNO"                 => "Codigo interno",
    "PRIMER_NOMBRE"                  => "Primer nombre",
    "SEGUNDO_NOMBRE"                 => "Segundo nombre",
    "PRIMER_APELLIDO"                => "Primer apellido",
    "SEGUNDO_APELLIDO"               => "Segundo apellido",
    "RAZON_SOCIAL"                   => "Razón social",
    "NOMBRE_COMERCIAL"               => "Nombre comercial",
    "REGIMEN"                        => "Régimen",
    "REGIMEN_COMUN"                  => "Régimen común",
    "REGIMEN_SIMPLIFICADO"           => "Régimen simplificado",
    "RETIENE_FUENTE"                 => "Realiza retencion en la fuente",
    "AUTORETENEDOR"                  => "Es autoretenedor",
    "RETIENE_IVA"                    => "Retiene IVA",
    "RETIENE_ICA"                    => "Retiene ICA",
    "GRAN_CONTRIBUYENTE"             => "Gran contribuyente",
    "PAIS"                           => "Pais",
    "DEPARTAMENTO"                   => "Departamento",
    "MUNICIPIO"                      => "Municipio expedición",
    "PESTANA_UBICACION_TERCERO"      => "Ubicación",
    "PESTANA_PAGOS"                  => "Pagos",
    "LOCALIDAD"                      => "Barrio ó corregimiento",
    "DIRECCION"                      => "Dirección",
    "TELEFONO_PRINCIPAL"             => "Telefono principal",
    "FAX"                            => "Fax",
    "CELULAR"                        => "Celular",
    "CORREO"                         => "Correo electronico",
    "SITIO_WEB"                      => "Pagina de internet(Web)",
    "PESTANA_PROVEEDOR"              => "Comercial",
    "ACTIVIDAD_PRINCIPAL"            => "Actividad económica principal",
    "ACTIVIDAD_SECUNDARIA"           => "Actividad económica secundaria",
    "FABRICANTE"                     => "Fabrica la mercancia",
    "DISTRIBUIDOR"                   => "Comercializa varias marcas",
    "SERVICIOS_TECNICOS"             => "Proveedor de servicios tecnicos",
    "TRANSPORTE"                     => "Proveedor de transporte",
    "PUBLICIDAD"                     => "Proveedor de publicidad",
    "SERVICIOS_ESPECIALES"           => "Proveedor de servicios especiales",
    "TIPO_SERVICIO"                  => "Tipo de servicio",
    "FECHA_INICIO_COBRO"             => "Fecha de inicio de cobro",
    "FORMA_PAGO_CONTADO"             => "Forma pago de contado",
    "FORMA_PAGO_CREDITO"             => "Forma pago de credito",
    "TASA_PAGO_CREDITO"              => "Tasa de pago credito",
    "PRIMERA_CUOTA"                  => "Primera cuota de % por vencimiento",
    "ULTIMA_CUOTA"                   => "Ultima cuota de % por vencimiento",
    "PAGOS_ANTICIPADOS"              => "Autoriza pagos anticipados",
    "PAGOS_EFECTIVOS"                => "Autoriza pagos efectivos",
    "TRANSFERENCIA_ELECTRONICA"      => "Autoriza transferencia electronica",
    "TARJETA_CREDITO"                => "Autoriza pagos tarjeta credito",
    "TRIANGULACION_BANCARIA"         => "Autoriza pagos triangulacion bancaria",
    "TIEMPO_RESPUESTA"               => "Tiempo de respuesta en dias",
    "PORCENTAJE_FLETE"               => "Porcentaje flete",
    "VALOR_FLETE"                    => "Valor flete",
    "PORCENTAJE_SEGURO"              => "Porcentaje seguro",
    "VALOR_SEGURO"                   => "Valor seguro",
    "ERROR_EXISTE_CODIGO"            => "Ya existe un proveedor con ese codigo ",
    "NATURAL"                        => "Natural",
    "JURIDICA"                       => "Juridica",
    "INTERNO"                        => "Codigo interno",
    "NO_FABRICA"                     => "No fabrica mercancia",
    "FABRICA"                        => "Fabrica mercancia",
    "UNA_MARCA"                      => "Comercializa solo una marca",
    "VARIAS_MARCAS"                  => "Comercializa varias marcas",
    "FECHA_FACTURA"                  => "Fecha de la factura",
    "FECHA_RECIBO"                   => "Fecha de recibida la mercancia",
    "DISTRIBUIDO"                    => "Distribuido",
    "PRIMERA_CUOTA"                  => "Primera cuota",
    "SEPARADO"                       => "Separado",
    "FORMA_IVA"                      => "Forma de pago de IVA",
    "PESTANA_CUENTAS"                => "Cuentas",
    "BANCO"                          => "Banco",
    "CUENTA"                         => "Cuenta",
    "TIPO_CUENTA"                    => "Tipo de cuenta",
    "AHORROS"                        => "Ahorros",
    "CORRIENTE"                      => "Corriente",
    "NATURAL_COMERCIANTE"            => "Natural comerciante",
    "DIGITO_VERIFICACION"            => "Digito de verificación",
    "SIN_CUENTAS"                    => "Este proveedor actualmente no posee cuentas bancarias asignadas",
    "AYUDA_FORMA_IVA"                => "Forma en que el proveedor acepta el pago del IVA en las compras",
    "AYUDA_PROVEEDOR"                => "Digite el documento de identidad",
    "AYUDA_PRIMER_NOMBRE"            => "Digite el primer nombre",
    "AYUDA_SEGUNDO_NOMBRE"           => "Digite el segundo nombre",
    "AYUDA_PRIMER_APELLIDO"          => "Digite el primer apellido",
    "AYUDA_SEGUNDO_APELLIDO"         => "Digite el segundo apellido",
    "AYUDA_RAZON_SOCIAL"             => "Digite la razon social o nombre de la empresa",
    "AYUDA_NOMBRE_COMERCIAL"         => "Nombre comercial utilizado por el proveedor",
    "AYUDA_DOCUMENTO_PAIS"           => "Pais donde pertenece el documento de identidad del tercero",
    "AYUDA_DOCUMENTO_DEPARTAMENTO"   => "Departamento donde pertenece el documento de identidad del tercero",
    "AYUDA_DOCUMENTO_MUNICIPIO"      => "Municipio donde pertenece el documento de identidad del tercero",
    "AYUDA_RESIDENCIA_PAIS"          => "Pais donde se ubica el proveedor",
    "AYUDA_RESIDENCIA_DEPARTAMENTO"  => "Departamento donde se ubica el proveedor",
    "AYUDA_RESIDENCIA_MUNICIPIO"     => "Municipio donde se ubica el proveedor",
    "AYUDA_LOCALIDAD"                => "Seleccione el barrio o corregiemiento donde se ubica el proveedor",
    "AYUDA_DIRECCION"                => "Direccion donde se ubica el proveedor",
    "AYUDA_TELEFONO_PRINCIPAL"       => "Telefono principal, digite indicativo si lo requiere",
    "AYUDA_FAX"                      => "Fax, si el proveedor no tiene fax puede colocar otro numero de telefono",
    "AYUDA_CELULAR"                  => "Numero de celular del proveedor",
    "AYUDA_CORREO"                   => "Correo electronico del proveedor, EJEPMLO: micorreo@gmail.com",
    "AYUDA_SITIO_WEB"                => "Pagina web del proveedor, EJEMPLO: www.mipagina.com",
    "AYUDA_ACTIVIDAD_PRINCIPAL"      => "Actividad económica principal",
    "AYUDA_ACTIVIDAD_SECUNDARIA"     => "Actividad económica secundaria",
    "AYUDA_MAX_CUOTAS_CONTADO"       => "Número máximo de cuotas dadas por el proveedor para pago de contado",
    "AYUDA_TASA_PAGO_CONTADO"        => "Tasa de interés que cobra el proveedor para pagos de contado",
    "AYUDA_MAX_CUOTAS_CREDITO"       => "Número máximo de cuotas dado por el proveedor para pago a crédito",
    "AYUDA_TASA_CUOTAS_CREDITO"      => "Tasa de interés que cobra el proveedor para pagos a crédito",
    "AYUDA_TIEMPO_RESPUESTA"         => "Número de días que tarda para enviar una mercancía o prestar un servicio",
    "AYUDA_PORCENTAJE_FLETE"         => "Porcentaje sobre la compra",
    "AYUDA_VALOR_FLETE"              => "Digite el valor flete si el proveedor lo cobra en la factura",
    "AYUDA_PORCENTAJE_SEGURO"        => "Porcentaje sobre la compra",
    "AYUDA_VALOR_SEGURO"             => "Digite el valor del seguro si el proveedor lo cobra en la factura",
    "AYUDA_PRIMERA_CUOTA"            => "Digite el porcentaje de la primera cuota por vencimiento",
    "AYUDA_ULTIMA_CUOTA"             => "Digite el porcentaje de la ultima cuota por vencimiento",
    "ERROR_EXISTE_TERCERO"           => "Ya existe un proveedor con ese documento",
    "DATO_VACIO"                     => "",
    "AYUDA_LOCALIDAD"                => "Localidad donde se encuentra ubicado el proveedor",
    "AYUDA_REGIMEN"                  => "Seleccione el regimen tributario",
    "AYUDA_TIPO_SERVICIO"            => "Seleccione el tipo de servicio",
    "AYUDA_INICIO_COBRO"             => "Seleccione la fecha de inicio del cobro",
    "AYUDA_PAGO_CONTADO"             => "Seleccione la forma de pago de contado",
    "AYUDA_PAGO_CREDITO"             => "Seleccione la forma de pago a credito",
    "AYUDA_BANCO"                    => "Digite el nombre del banco y seleccionelo de la lista desplegable",
    "AYUDA_CUENTA"                   => "Numero de la cuenta bancaria",
    "TITULO_DESCUENTO_LINEA"         => "DESCUENTO DE LINEA",
    "VALOR_NETO_UNITARIO"            => "Desde el valor unitario",
    "VALOR_NETO_TOTAL"               => "Desde el valor total",
    "TITULO_DESCUENTO_GLOBAL"        => "DESCUENTO GLOBAL",
    "NETO_DESDE_UNITARIO"            => "Desde el valor unitario",
    "NETO_CON_TOTAL"                 => "Desde el valor total",
    "NETO_FINAL_FACTURA"             => "Al final de la factura",
    "LINEA_1"            			 => "Desde el valor unitario",
    "LINEA_2"            			 => "Desde el valor total",
    "GLOBAL_1"           			 => "Desde el valor unitario",
    "GLOBAL_2"           			 => "Desde el valor total",
    "GLOBAL_3"          			 => "Al final de la factura",
     /*** Verificar datos vacios ***/
    "DOCUMENTO_IDENTIDAD_VACIO"      => "Digite el documento de identidad",
    "TIPO_PERSONA_VACIO"             => "Seleccione el tipo de persona",
    "DESCRIPCION_VACIO"              => "Digite la descripcion para el banco",
    "MUNICIPO_DOCUMENTO_VACIO"       => "Ingrese el mucipio para el documento de tercero",
    "LOCALIDAD_VACIO"                => "Ingrese el barrio y/o corregimiento del tercero",
    "DIRECCION_VACIO"                => "Ingrese la dirección para el tercero",
    "DIRECCION_DIRECCIONES_VACIO"    => "Ingrese la dirección en la pestaña de direcciones para el tercero",
    "TIPO_DOCUMENTO_VACIO"           => "Seleccione el tipo documento de identidad",
    "NOMBRE_RAZON_VACIO"             => "Debe ingresar el nombre o la razon social del tercero",
    "APELLIDO_VACIO"                 => "Debe ingresar minimo el primer apelido del tercero",
    "NOMBRE_VACIO"                   => "Debe ingresar minimo el primer nombre del tercero",
    "AUTORETENEDOR_ICA"              => "Autorenedor ICA",
    "DESPUES_LINEA"                  => "Despues de los descuentos en linea",
    "DESPUES_GLOBAL"                 => "Despues de los descuentos globales",
    "LIQUIDACION_TASA_CREDITO"       => "Forma de liquidacion tasa credito",
    "AYUDA_LIQUIDACION_TASA_CREDITO" => "Seleccione la forma de liquidacion de la tasa credito",
    "NO_EXISTEN_REGISTROS"           => "No existen registros en las siguientes tablas:\n",
    "ERROR_CREAR_ACTIVIDADES"        => "-Actividades economica\n",
    "ERROR_CREAR_TIPOS_DOCUMENTOS"   => "-Tipos de documento de identidad\n",
    "ERROR_CREAR_SERVICIOS"          => "-Servicios\n",
    "ERROR_CREAR_MUNICPIOS"          => "-Municipios\n",
    "ERROR_CREAR_LOCALIDADES"        => "-Localidades(Barrios/Corregimiento)\n",
    "ERROR_PLAZOS_PAGOS"             => "-Plazos de pago\n",
    "CREAR_REGISTROS"                => "\nDebe crear por lo menos un registro para las tablas anteriores",
    "ERROR_ELIMINAR_CUENTA"          => "La cuenta no puede ser eliminada porque ya tiene movimientos contables",
    "CUENTA_ELIMINADA"               => "Cuenta eliminada con exito"
);
?>
