<?php
/**
*
* Copyright (C) 2020 Jobdaily
*
* Este archivo es parte de:
* Jobdaily:: Sofware empresarial a la medida
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los terminos de la Licencia Publica General GNU
* publicada por la Fundacion para el Software Libre, ya sea la version 3
* de la Licencia, o (a su eleccion) cualquier version posterior.
*
* Este programa se distribuye con la esperanza de que sea util, pero
* SIN GARANTIA ALGUNA; ni siquiera la garantia implicita MERCANTIL o
* de APTITUD PARA UN PROPOSITO DETERMINADO. Consulte los detalles de
* la Licencia Publica General GNU para obtener una informacion mas
* detallada.
*
* Deberia haber recibido una copia de la Licencia Publica General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(
    "GESTINEM"                              => "Ingreso de empleados",
    "ADICINEM"                              => "Adicionar Empleados",
    "CONSINEM"                              => "Consultar Empleados",
    "MODIINEM"                              => "Modificar Empleados",
    "RETIINEM"                              => "Retirar Empleados",
    "LISTINEM"                              => "Listado de Empleados",
    "PESTANA_BASICA"                        => "General",
    "NUMERO_DOCUMENTO"                      => "Numero de documento",
    "NOMBRE_COMPLETO"                       => "Nombres",
    "ESTADO"                                => "Estado",
    "FECHA_INICIAL"                         => "Fecha de inicio",
    "TURNO_LABORAL"                         => "Turno laboral",
    "AUXILIO_TRANSPORTE"                    => "Recibe auxilio de transporte",
    "SI"                                    => "Si",
    "NO"                                    => "No",
    "PLANILLA"                              => "Planilla",
    "AYUDA_PLANILLA"                        => "Descripcion de la planilla con que se liquida al empleado",
    "AYUDA_NOMBRE_COMPLETO"                 => "Nombre completo del empleado",
    "AYUDA_FECHA_INICIAL"                   => "Fecha en que inicia labores el empleado",
    "AYUDA_TURNO_LABORAL"                   => "Turno en el cual realiza labores el empleado",

    "AYUDA_TIPO_CONTRATO"                   => "Descripción del tipo de contrato",
    "AYUDA_CARGO"                           => "Cargo que desempeñara en la empresa",
    "AYUDA_DEPARTAMENTOS"                   => "Descripción del departamento donde va a laborar",
    "AYUDA_SECCION"                         => "Descripción de la sección donde va a laborar",
    "AYUDA_RIESGO_PROFESIONAL"              => "Porcentaje para liquidar el riesgo profesional",
    "AYUDA_ANEXO_CONTABLE"                  => "Descripción que identifica el anexo contable",
    "AYUDA_AUXILIAR_CONTABLE"               => "Descripción que identifica el auxiliar contable (centro de costos)",
    "AYUDA_HORAS_DIA"                       => "Número de horas diarias a laborar",
    "AYUDA_DIAS_MES"                        => "Número de días al mes a laborar",
    "AYUDA_SALARIO"                         => "Salario base de liquidación",
    "AYUDA_SUCURSAL_LABORA"                 => "Almacen donde va a laborar",

    "AYUDA_ENTIDAD_SALUD"                   => "Entidad de salud donde se encuentra vinculado el empleado",
    "AYUDA_FECHA_SALUD"                     => "Fecha de vinculacion a la entidad de salud",
    "AYUDA_DIRECCION_ATIENDEN"              => "Dirección donde atiende al empleado",
    "AYUDA_DIRECCION_URGENCIA"              => "Dirección donde atiende al empleado en caso de urgencia",
    "AYUDA_ENTIDAD_PENSION"                 => "Entidad del fondo de pensiones donde se encuentra vinculado el empleado",
    "AYUDA_FECHA_PENSION"                   => "Fecha de vinculacion al fondo de pensiones",

    "PESTANA_CONTRATO"                      => "Contrato",
    "TIPO_CONTRATO"                         => "Tipo contrato",
    "CARGO"                                 => "Cargo",
    "FECHA_CONTRATO"                        => "Fecha contrato",
    "DEPARTAMENTOS"                         => "Departamento",
    "SECCION"                               => "Seccion",
    "RIESGO_PROFESIONAL"                    => "Riesgo profesional",
    "ANEXO_CONTABLE"                        => "Anexo",
    "AUXILIAR_CONTABLE"                     => "Auxiliar",
    "HORAS_DIARIAS"                         => "Horas Diarias",
    "SALARIOS"                              => "Salario",
    "SUCURSAL_LABORA"                       => "Almacen",

    "PESTANA_PARAFISCALES"                  => "Parafiscales",
    "ENTIDAD_SALUD"                         => "Entidad salud",
    "DIRECCION_ATIENDEN"                    => "Direccion atencion",
    "DIRECCION_URGENCIA"                    => "Direccion urgencia",
    "FECHA_INICIA"                          => "Fecha inicio",
    "ENTIDAD_PENSION"                       => "Entidad pension",
    "AUXILIARES_NO"                         => "No tiene",

    "PESTANA_RETIRO"                        => "Retiro",
    "FECHA_RETIRO"                          => "Fecha de retiro",
    "MOTIVO_RETIRO"                         => "Motivo retiro",
    "AYUDA_MOTIVO_RETIRO"                   => "Motivo por el cual se retira al empleado de la empresa",
    "ACTIVO"                                => "Activo",
    "RETIRADO"                              => "Retirado",
    "RETIRO"                                => "Retirar",

    "PESTANA_TRANSACCIONES_CONTABLES"       => "Otros ingresos",
    "TRANSACCION_CONTABLE"                  => "Transaccion contable",
    "AYUDA_TRANSACCION_CONTABLE"            => "Nombre de la transaccion contable que se le genera al empleado",
    "ID_TRANSACCION_CONTABLE"               => "Concepto contable",
    "PERIODO_PAGO"                          => "Periodo de pago",
    "CONCEPTO_CONTABLE"                     => "Concepto contable",
    "MENSUAL"                               => "Mensual",
    "SALARIOS_MENSUAL"                      => "Salario mensual",
    "SALARIO_DIARIO"                        => "Salario diario",

    "PRIMERA_QUINCENA"                      => "Primera quincena",
    "SEGUNDA_QUINCENA"                      => "Segunda quincena",
    "PROPORCIONAL_QUINCENA"                 => "Proporcional",
    "PRIMERA_SEMANA"                        => "Primera semana",
    "SEGUNDA_SEMANA"                        => "Segunda semana",
    "TERCERA_SEMANA"                        => "Tercera semana",
    "CUARTA_SEMANA"                         => "cuarta semana",
    "SEMANAL"                               => "Semanal",

    "PESTANA_TRANSACCIONES_TIEMPO"          => "Transacciones tiempo",
    "HORAS_EXTRAS"                          => "Horas extras",
    "AYUDA_EXTRAS_NORMALES"                 => "Seleccione la transaccion de horas extras normales si al empleado se la cancelaran",
    "HORAS_EXTRAS_NOCTURNAS"                => "Horas extras nocturnas",
    "AYUDA_EXTRAS_NOCTURNAS"                => "Seleccione la transaccion de horas extras nocturnas si al empleado se la cancelaran",
    "HORAS_EXTRAS_DOMINGOS_FESTIVOS"        => "Horas extras domingos y festivos",
    "AYUDA_EXTRAS_DOMINICALES"              => "Seleccione la transaccion de horas extras dominicales si al empleado se la cancelaran",
    "HORAS_EXTRAS_DOMINGOS_FESTIVOS_NOCHE"  => "Horas extras domingos y festivos nocturnas",
    "AYUDA_EXTRAS_DOMINICALES_NOCTURNAS"    => "Seleccione la transaccion de horas extras dominicales y festivos nocturnas si al empleado se la cancelaran",
    "HORAS_NORMALES"                        => "Horas normales",
    "AYUDA_HORAS_NORMALES"                  => "Seleccione la transaccion de horas normales",

    "ERROR_VACIO_EMPLEADO"                  => "Error, No ha seleccionado nombres. Pestaña General",
    "ERROR_EXISTE_EMPLEADO"                 => "Ya existe un empleado con este código",
    "ERROR_VACIO_SALARIO_CODIGO"            => "Por favor ingrese un valor al salario",
    "ERROR_ELIMINAR_EMPLEADO"               => "El registro esta siendo utilizado por otro modulo",
    "ERROR_RETIRAR_VACIO"                   => "Por favor seleccione el elemento que desea retirar",
    "ERROR_VACIO_TURNO"                     => "No existen turnos laborales creados, debe crear almenos uno",
    "ERROR_VACIO_PLANILLA"                  => "No existen planillas creadas, debe crear almenos una",
    "ERROR_VACIO_SUCURSALES"                => "No existen almacenes creados, debe crear almenos una",
    "ERROR_VACIO_TIPOS_COTRATO"             => "No existen tipos de contratos creados, debe crear almenos uno",
    "ERROR_VACIO_CARGOS"                    => "No existen cargos creados, debe crear almenos uno",
    "ERROR_VACIO_DEPARTAMENTOS"             => "No existen departamentos de empresa creados, debe crear almenos uno",
    "ERROR_VACIO_SECCIONES"                 => "No existen secciones de departamentos creados, debe crear almenos una",
    "ERROR_VACIO_ANEXOS"                    => "No existen anexos contables, debe crear almenos uno",
    "ERROR_VACIO_TRANSACCIONES"             => "No existen Transacciones de tiempo, debe crear almenos una",
    "AYUDA_EMPRESAS"                        => "Empresa a la que pertenece el almacén",
    "EMPRESA"                               => "Empresa",
    "ERROR_EXISTE_TRANSACCION"              => "Ya existe la transaccion contablen la en tabla",
    "ERROR_VACIO_SUCURSALES_CODIGO"         => "Error, No ha seleccionado un almacen. Pestaña General",
    "ERROR_VACIO_SECCIONES_CODIGO"          => "Error, No ha seleccionado una sección. Pestaña Contrato",
    "ERROR_VACIO_SECCIONES_CODIGO"          => "Error, No ha Ingresado el salario mensual. Pestaña Contrato",
    "PAGUELO_POR_LEY_CON_DESCUENTO"         => "Descuento tiempos no laborados",
    "PAGUELO_POR_LEY_SIN_DESCUENTO"         => "Sin descuento tiempos no laborados",
    "PAGELE_MAYOR_2_SALARIO_CON_DESCUENTO"  => "Pago mayor a dos SMLV con descuentos",
    "PAGELE_MAYOR_2_SALARIO_SIN_DESCUENTO"  => "Pago mayor a dos SMLV sin descuentos",
    "UBICACION"                             => "Ubicación",
    "FECHA_VENCIMIENTO"                     => "fecha de vencimiento",
    "AYUDA_FECHA_VENCIMIENTO"               => "Fecha en la cual se termina el contrato",
    "TRANSACCION_CONTABLE_SALARIO"          => "Transaccion contable salario",
    "TRANSACCION_CONTABLE_AUXILIO"          => "Transaccion contable auxilio transporte",
    "TRANSACCION_CONTABLE_SALUD"            => "Transaccion contable salud",
    "TRANSACCION_CONTABLE_PENSION"          => "Transaccion contable pension",
    "TRANSACCION_FIJAS"                     => "Transaccion fijas",
    "OTRAS_TRANSACCION"                     => "Otras transaccion",
    "HORAS_RECARGO_NOCTURNA"                => "Horas recargo nocturna",
    "AYUDA_HORAS_RECARGO_NOCTURNA"          => "Seleccione la transaccion de horas recargo nocturnas si al empleado se la cancelaran",
    "HORAS_DOMINICALES"                     => "Horas domingos y festivos",
    "AYUDA_HORAS_DOMINICALES"               => "Seleccione la transaccion de horas domingo y festivo si al empleado se la cancelaran",
    "HORAS_RECARGO_NOCHE_DOMINICAL"         => "Horas recargo domingos y festivos noche ",
    "AYUDA_HORAS_RECARGO_NOCHE_DOMINICAL"   => "Seleccione la transaccion de horas recargo nocturnas domingo y festivo si al empleado se la cancelaran",
    "ERROR_VACIO_FECHA_INICIAL_SALUD"       => "Error, No ha seleccionado una fecha inicio de salud. Pestaña Parafiscales",
    "ERROR_VACIO_FECHA_INICIAL_PENSION"     => "Error, No ha seleccionado una fecha inicio de pension. Pestaña Parafiscales",
    "ERROR_VACIO_TRANSACCION_SALARIO"       => "Error, No ha seleccionado una transaccion para salario. Pestaña Transacciones contables",
    "ERROR_VACIO_AUXILIAR"                  => "Error, Debe seleccionar un Anexo y un Auxiliar . Pestaña Transacciones contables",
    "AYUDA_NOMBRE_COMPLETO_DEL_JEFE"        => "Nombre del jefe del la seccion",
    "NOMBRE_JEFE"                           => "Nombre del jefe",
    "ERROR_SALARIO_INTEGRAL"                => "Error, El tipo de contrato selecciona tiene relacionado un tipo de salario Integral, el salario mensual debe ser mayor a $ salarios minimo vigentes",

    "CONFIRMAR_RETIRO"                      => "Confirmar retiro",
    "AYUDA_FECHA_RETIRO"                    => "Seleccione la fecha de retiro",
    "EMPLEADO_RETIRADO"                     => "Empleado retirado con exito",
    "FALLA_EMPLEADO_RETIRADO"               => "Error, el empleado no pudo ser retirado",
    "ERROR_EMPLEADO_RETIRADO"               => "El empleado ya fue retirado",
    "FORMA_PAGO_AUXILIO"                    => "Forma de pago de auxilio de transporte",
    "DESCRIPCION"                           => "Descripcion",
    "MENSAJE"                               => "Por favor seleccione una de las siguientes opcion",
    "TRANSLADO_CONTRATO_SUCURSAL"           => "Realizar translado de almacén",
    "CAMBIO_CONTRATO"                       => "Renovar contrato de empleado",
    "CAMBIAR_PARAFISCALES"                  => "Cambiar entidades parafiscales",
    "CAMBIAR_INGRESO_VARIOS_EMPLEADO"       => "Cambiar ingresos varios empleados",
    "FECHA_INICIAL_CAMBIOS"                 => "Fecha en que inician los cambios",
    "FECHA_RENOVACION_CONTRATO"             => "Fecha de inicio de contrato",
    "FECHA_INICIA_SUCURSAL"                 => "Fecha almacen",
    "FECHA_INGRESO"                         => "Fecha ingreso",
    "FECHA_NACIMIENTO"                      => "Fecha nacimiento",
    "ESTADO_2"                              => "Retirado",
    "ESTADO_1"                              => "Activo",
    "DESDE_HASTA"                           => "Desde&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hasta",
    "ARCHIVO_PLANO"                         => "Archivo plano para excel",
    "ARCHIVO_PDF"                           => "Pdf",
    "TIPO_LISTADO"                          => "Tipo de listado",
    "AYUDA_TIPO_LISTADO"                    => "Seleccione el tipo de listado a generar",
    "MOSTRAR_SALARIO"                       => "Mostrar salario",
    "MODIFICAR_TRANSACCIONES"               => "Modificar Transacciones",
    "OPCIONES"                              => "Opciones",
    "VALOR_INGRESO"                         => "Valor",
    "VACIO_VALOR_VARIO"                     => "Porfavor ingrese un valor.",
    ////////MESAJES PREFERENCIAS/////////
    "ERROR_MENSAJE_PREFERENCIAS"            => "Por favor verifique que exista las siguientes preferencias : \n \n ",
    "PRERENCIA_MINIMO_VALOR_INGRESO_VARIOS" => " - Preferecia por empresa donde la variable sea valor_minimo_ingresos_varios \n ",
    ////////////////////////////////////
    "AYUDA_REMOVER_TRASACCION"              => "Remover transaccion ",
    "AYUDA_MODIFICAR_TRASACCION"            => "Modificar transaccion ",
    "MINIMO_VALOR_INGRESO_VARIOS"           => "El el valor minimo de la transaccion es ",
    "FECHA_INICIO_TRANSACCION"              => "Fecha inicio",
    "MODIFICAR_SALARIO"                     => "Modificar Salario",
    "ERROR_MODIFICAR_SALARIO_EMPLEADO"      => "Se ha generado un error al momento de registrar  el nuevo salario",
    "ERROR_VACIO_TRANSACCION_AUXILIO"       => "Es necesario registrar una transaccion de auxilio de transporte",
    "PESTANA_MODIFICAR_SALARIO"             => "Datos Salario",
    "FECHA_INICIA_SALARIO"                  => "fecha_inicio_salario",
    "AYUDA_FECHA_INICIA_SALARIO"            => "Fecha de en el que inicia a regir el nuevo salario",
    "DIAS_MES"                              => "dias mes",
    "HORAS_MES"                             => "Horas del mes",
    "AYUDA_DIAS_MES"                        => "Numero de dias que trabajara en el mes",
    "AYUDA_HORAS_MES"                       => "Numero de horas que trabajara en el mes",
    "ERROR_VACIO_DIAS_MES"                  => "Error, No ha ingresado dias del mes. Pestaña Contrato",
    "ERROR_VACIO_HORAS_MES"                 => "Error, No ha ingresado horas del mes. Pestaña Contrato",
    "ERROR_HORAS_NO_CONCUERDAN_DIAS"        => "El numero de horas ingresada no concuerdan con los dias",
    "ERROR_PREFERENCIAS_VACIAS"             => "Las siguientes preferencias globales no han sido creadas:\n\n",
    "PREFERENCIA_INTEGRAL_VACIA"            => "- Salario integral",
    "PREFERENCIA_MINIMO_INGVAR_VACIA"       => "- Valor minimo de ingresos varios",
    "FECHA_RETROACTIVO"                     => "Fecha retroactivo",
    "AYUDA_FECHA_RETROACTIVO"               => "Seleccione la fecha a partir de la cual se hace salario retroactivo"
);
?>
